package org.dbplatform.common.sql;

import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Function names that are SQL built-ins in Oracle, PostgreSQL, SQL Server or H2 and therefore never
 * reported as routines. Not exhaustive; unknown built-ins may surface as (unresolvable) routines.
 */
final class SqlBuiltins {

    private static final Set<String> FUNCTIONS = Set.copyOf(List.of(
            // aggregates / analytics
            "COUNT", "COUNT_BIG", "SUM", "MIN", "MAX", "AVG", "MEDIAN", "STDDEV", "STDDEV_POP", "STDDEV_SAMP",
            "VARIANCE", "VAR_POP", "VAR_SAMP", "LISTAGG", "STRING_AGG", "ARRAY_AGG", "GROUP_CONCAT", "XMLAGG",
            "JSON_AGG", "JSONB_AGG", "JSON_ARRAYAGG", "JSON_OBJECTAGG", "JSON_OBJECT", "JSON_ARRAY", "JSON_VALUE",
            "JSON_QUERY", "JSON_TABLE", "JSON_EXISTS", "JSON_BUILD_OBJECT", "JSONB_BUILD_OBJECT", "JSON_BUILD_ARRAY",
            "JSONB_BUILD_ARRAY", "TO_JSON", "TO_JSONB", "JSON_EXTRACT_PATH", "JSONB_EXTRACT_PATH", "ROW_NUMBER",
            "RANK", "DENSE_RANK", "PERCENT_RANK", "CUME_DIST", "NTILE", "LEAD", "LAG", "FIRST_VALUE", "LAST_VALUE",
            "NTH_VALUE", "RATIO_TO_REPORT", "PERCENTILE_CONT", "PERCENTILE_DISC", "MODE", "BOOL_AND", "BOOL_OR",
            "EVERY", "BIT_AND", "BIT_OR", "BIT_XOR", "APPROX_COUNT_DISTINCT", "GROUPING", "GROUPING_ID", "COLLECT",
            "WM_CONCAT", "CORR", "COVAR_POP", "COVAR_SAMP", "REGR_SLOPE", "REGR_INTERCEPT", "REGR_COUNT",
            // null / conditional
            "NVL", "NVL2", "COALESCE", "DECODE", "NULLIF", "GREATEST", "LEAST", "ISNULL", "IIF", "CHOOSE", "LNNVL",
            "NANVL", "IFNULL", "CASEWHEN",
            // string
            "UPPER", "LOWER", "INITCAP", "SUBSTR", "SUBSTRB", "SUBSTRING", "INSTR", "INSTRB", "CHARINDEX", "PATINDEX",
            "LENGTH", "LENGTHB", "LEN", "DATALENGTH", "CHAR_LENGTH", "CHARACTER_LENGTH", "OCTET_LENGTH", "BIT_LENGTH",
            "TRIM", "LTRIM", "RTRIM", "BTRIM", "REPLACE", "TRANSLATE", "CONCAT", "CONCAT_WS", "LPAD", "RPAD", "REPEAT",
            "REPLICATE", "REVERSE", "LEFT", "RIGHT", "SPLIT_PART", "STRING_TO_ARRAY", "ARRAY_TO_STRING", "STRING_SPLIT",
            "POSITION", "STRPOS", "OVERLAY", "ASCII", "CHR", "CHAR", "NCHAR", "UNICODE", "SOUNDEX", "DIFFERENCE",
            "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR", "REGEXP_INSTR", "REGEXP_COUNT", "REGEXP_MATCH",
            "REGEXP_MATCHES", "REGEXP_SPLIT_TO_TABLE", "REGEXP_SPLIT_TO_ARRAY", "QUOTE_IDENT", "QUOTE_LITERAL",
            "QUOTE_NULLABLE", "QUOTENAME", "FORMAT", "FORMATMESSAGE", "SPACE", "STUFF", "STR", "TO_CHAR", "TO_NCHAR",
            "TO_CLOB", "TO_NCLOB", "TO_LOB", "TO_BLOB", "RAWTOHEX", "HEXTORAW", "UTL_RAW", "MD5", "SHA1", "SHA2",
            "HASHBYTES", "ENCODE", "DECODE_BASE64", "ENCODE_BASE64", "ORA_HASH", "STANDARD_HASH", "DBMS_RANDOM",
            "RANDOM", "RAND", "SETSEED", "GEN_RANDOM_UUID", "UUID_GENERATE_V4", "NEWID", "NEWSEQUENTIALID", "SYS_GUID",
            "RANDOM_UUID", "ASCIISTR", "UNISTR", "COMPOSE", "DECOMPOSE", "NLSSORT", "NLS_UPPER", "NLS_LOWER",
            "NLS_INITCAP", "VSIZE", "DUMP", "EMPTY_CLOB", "EMPTY_BLOB", "LIKE", "STARTS_WITH", "LEFT_PAD",
            // numeric
            "ABS", "MOD", "POWER", "SQRT", "CBRT", "EXP", "LN", "LOG", "LOG10", "LOG2", "FLOOR", "CEIL", "CEILING",
            "ROUND", "TRUNC", "TRUNCATE", "SIGN", "PI", "SIN", "COS", "TAN", "ASIN", "ACOS", "ATAN", "ATAN2", "SINH",
            "COSH", "TANH", "DEGREES", "RADIANS", "WIDTH_BUCKET", "BITAND", "BITOR", "BITXOR", "BIT_COUNT", "DIV",
            "REMAINDER", "SCALE", "NUMTODSINTERVAL", "NUMTOYMINTERVAL", "TO_NUMBER", "TO_BINARY_DOUBLE",
            "TO_BINARY_FLOAT", "SQUARE", "ROWNUM", "LEVEL",
            // date / time
            "SYSDATE", "SYSTIMESTAMP", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "LOCALTIME",
            "LOCALTIMESTAMP", "NOW", "CLOCK_TIMESTAMP", "STATEMENT_TIMESTAMP", "TRANSACTION_TIMESTAMP", "TIMEOFDAY",
            "GETDATE", "GETUTCDATE", "SYSDATETIME", "SYSUTCDATETIME", "SYSDATETIMEOFFSET", "SYS_EXTRACT_UTC",
            "TO_DATE", "TO_TIMESTAMP", "TO_TIMESTAMP_TZ", "TO_YMINTERVAL", "TO_DSINTERVAL", "ADD_MONTHS",
            "MONTHS_BETWEEN", "LAST_DAY", "NEXT_DAY", "NEW_TIME", "FROM_TZ", "TZ_OFFSET", "SESSIONTIMEZONE",
            "DBTIMEZONE", "EXTRACT", "DATE_PART", "DATE_TRUNC", "DATE_BIN", "AGE", "MAKE_DATE", "MAKE_TIME",
            "MAKE_TIMESTAMP", "MAKE_TIMESTAMPTZ", "MAKE_INTERVAL", "TO_TIMESTAMP_TZ", "JUSTIFY_DAYS", "JUSTIFY_HOURS",
            "JUSTIFY_INTERVAL", "ISFINITE", "DATEADD", "DATEDIFF", "DATEDIFF_BIG", "DATEPART", "DATENAME", "DAY",
            "MONTH", "YEAR", "HOUR", "MINUTE", "SECOND", "QUARTER", "WEEK", "DAYOFWEEK", "DAYOFYEAR", "DAYNAME",
            "MONTHNAME", "EOMONTH", "DATEFROMPARTS", "DATETIMEFROMPARTS", "DATETIME2FROMPARTS", "TIMEFROMPARTS",
            "SWITCHOFFSET", "TODATETIMEOFFSET", "ISDATE", "TIMESTAMPADD", "TIMESTAMPDIFF", "DATE", "TIME",
            "TIMESTAMP", "INTERVAL", "TO_UTC_TIMESTAMP_TZ", "ORA_DST_CONVERT",
            // conversion / type
            "CAST", "CONVERT", "TRY_CAST", "TRY_CONVERT", "TRY_PARSE", "PARSE", "TO_HEX", "TO_ASCII", "BIN_TO_NUM",
            "ROWIDTOCHAR", "CHARTOROWID", "CHARTOROWIDLE", "SCN_TO_TIMESTAMP", "TIMESTAMP_TO_SCN", "TREAT",
            "VALIDATE_CONVERSION", "ISNUMERIC", "ISJSON", "PG_TYPEOF", "TYPEOF", "ARRAY", "ARRAY_LENGTH",
            "ARRAY_UPPER", "ARRAY_LOWER", "ARRAY_APPEND", "ARRAY_PREPEND", "ARRAY_CAT", "ARRAY_REMOVE",
            "ARRAY_REPLACE", "ARRAY_POSITION", "ARRAY_POSITIONS", "ARRAY_FILL", "ARRAY_NDIMS", "ARRAY_DIMS",
            "CARDINALITY", "UNNEST", "GENERATE_SERIES", "GENERATE_SUBSCRIPTS", "ROW", "TABLE", "MULTISET",
            "HSTORE", "SET", "COLLECTION", "XMLELEMENT", "XMLFOREST", "XMLATTRIBUTES", "XMLTYPE", "XMLSERIALIZE",
            "XMLPARSE", "XMLQUERY", "XMLEXISTS", "XMLTABLE", "XMLCONCAT", "XMLCOMMENT", "XMLROOT", "XMLCAST",
            "EXTRACTVALUE", "UPDATEXML", "XMLSEQUENCE", "SYS_XMLGEN", "XMLCOLATTVAL", "XMLPI",
            // session / system
            "USER", "CURRENT_USER", "SESSION_USER", "SYSTEM_USER", "SUSER_SNAME", "SUSER_NAME", "USER_NAME",
            "ORIGINAL_LOGIN", "UID", "USERENV", "SYS_CONTEXT", "SYS_GUID", "ORA_ROWSCN", "ORA_INVOKING_USER",
            "ORA_INVOKING_USERID", "CURRENT_SCHEMA", "CURRENT_CATALOG", "CURRENT_DATABASE", "CURRENT_SETTING",
            "SET_CONFIG", "VERSION", "DB_NAME", "DB_ID", "OBJECT_ID", "OBJECT_NAME", "SCHEMA_NAME", "SCHEMA_ID",
            "SCOPE_IDENTITY", "IDENT_CURRENT", "LASTVAL", "CURRVAL", "NEXTVAL", "SETVAL", "NEXT_VALUE_FOR",
            "ROWCOUNT", "ERROR_NUMBER", "ERROR_MESSAGE", "ERROR_LINE", "ERROR_PROCEDURE", "ERROR_SEVERITY",
            "ERROR_STATE", "XACT_STATE", "HOST_NAME", "APP_NAME", "CONNECTIONPROPERTY", "SESSIONPROPERTY",
            "SERVERPROPERTY", "PG_BACKEND_PID", "PG_SLEEP", "TXID_CURRENT", "PG_CURRENT_XACT_ID",
            "INET_CLIENT_ADDR", "INET_SERVER_ADDR", "PG_ADVISORY_LOCK", "PG_ADVISORY_UNLOCK", "PG_TRY_ADVISORY_LOCK",
            "PG_ADVISORY_XACT_LOCK", "PG_TRY_ADVISORY_XACT_LOCK", "PG_NOTIFY", "LOCK_TIMEOUT", "SQLCODE", "SQLERRM",
            "SQL_VARIANT_PROPERTY", "COLUMNS_UPDATED", "UPDATE", "DELETE", "INSERT", "EXISTS", "ANY", "ALL", "SOME",
            "IN", "NOT", "AND", "OR", "BETWEEN", "IS", "NULL", "VALUES", "DEFAULT", "LATERAL", "FILTER", "WITHIN",
            "OVER", "KEEP", "RESPECT", "IGNORE", "NULLS", "ORDER", "GROUP", "SEARCH", "DEPTH", "BREADTH", "CYCLE",
            "FULLTEXT", "CONTAINS", "FREETEXT", "CONTAINSTABLE", "FREETEXTTABLE", "OPENJSON", "OPENXML", "OPENQUERY",
            "OPENROWSET", "OPENDATASOURCE", "TO_TSVECTOR", "TO_TSQUERY", "PLAINTO_TSQUERY", "PHRASETO_TSQUERY",
            "WEBSEARCH_TO_TSQUERY", "TS_RANK", "TS_RANK_CD", "TS_HEADLINE", "SIMILARITY", "LEVENSHTEIN",
            "DBMS_LOB", "DBMS_OUTPUT", "LOWER_INC", "UPPER_INC", "ISEMPTY", "RANGE_MERGE", "NUM_NONNULLS", "NUM_NULLS",
            "COLLATE", "CONVERT_FROM", "CONVERT_TO", "PG_TOTAL_RELATION_SIZE", "PG_RELATION_SIZE", "PG_SIZE_PRETTY",
            "TO_REGCLASS", "OBJ_DESCRIPTION", "COL_DESCRIPTION", "FORMAT_TYPE", "PG_GET_SERIAL_SEQUENCE",
            "SYS_OP_MAP_NONNULL", "SYS_OP_C2C", "SYS_CONNECT_BY_PATH", "CONNECT_BY_ROOT", "ROWID", "BFILENAME",
            "TBL", "TABLES", "GUID", "IDENTITY", "ISNUMERIC", "CHECKSUM", "CHECKSUM_AGG", "BINARY_CHECKSUM",
            "COMPRESS", "DECOMPRESS", "STRING_ESCAPE", "TRANSLATE", "TRIM_ARRAY", "ARRAY_CONTAINS", "ARRAY_SLICE",
            "ARRAY_GET", "ARRAY_CONCAT", "CSVREAD", "CSVWRITE", "LINK_SCHEMA", "MEMORY_FREE", "MEMORY_USED",
            "DATABASE", "DATABASE_PATH", "H2VERSION", "SESSION_ID", "TRANSACTION_ID", "AUTOCOMMIT", "LOCK_MODE",
            "READONLY", "SCHEMA", "FILE_READ", "FILE_WRITE", "DISK_SPACE_USED", "SIGNAL", "ESTIMATED_ENVELOPE",
            "REGEXP_INSTR", "FORMAT_NUMBER", "XMLNODE", "XMLSTARTDOC", "XMLTEXT", "XMLCDATA", "LOCATE", "DIFFERENCE",
            "INSERT", "HEXTORAW", "RAWTOHEX", "SECURE_RAND", "ZERO", "TRUNCATE_VALUE", "CURRENT_SCHEMA", "CURRENT_PATH",
            "CURRENT_ROLE", "BIGINT", "INT", "INTEGER", "NUMBER", "VARCHAR", "VARCHAR2", "NVARCHAR", "NVARCHAR2",
            "CHAR", "DECIMAL", "NUMERIC", "FLOAT", "DOUBLE", "REAL", "BOOLEAN", "TEXT", "CLOB", "BLOB", "JSON",
            "JSONB", "UUID", "BYTEA", "SMALLINT", "TINYINT", "BIT", "MONEY", "DATETIME", "DATETIME2", "DATETIMEOFFSET",
            "SMALLDATETIME", "VARBINARY", "BINARY", "IMAGE", "XML", "GEOGRAPHY", "GEOMETRY", "HIERARCHYID",
            "SQL_VARIANT", "TIMESTAMPTZ", "TIMETZ", "INET", "CIDR", "MACADDR", "INTERVAL", "SERIAL", "BIGSERIAL",
            "OID", "NAME", "REGCLASS", "RAW", "LONG", "ROWVERSION", "SYSNAME"));

    private SqlBuiltins() {}

    static boolean isBuiltinFunction(String name) {
        return name != null && FUNCTIONS.contains(name.toUpperCase(Locale.ROOT));
    }
}
