apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dbp-gateway
  namespace: dbp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dbp-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dbp-proxy
  namespace: dbp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dbp-proxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dbp-control-plane
  namespace: dbp
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dbp-control-plane
