-- =====================================================================================
-- 10_schema.sql  --  Retail demo schema "sales" in database "sales" (PostgreSQL 17)
-- Mirrors demo/sql/oracle/10_schema.sql: same tables, columns and constraints (lower-case names).
-- =====================================================================================
\set ON_ERROR_STOP on
\connect sales

CREATE SCHEMA IF NOT EXISTS sales AUTHORIZATION sales;
SET ROLE sales;
SET search_path TO sales, public;

CREATE TABLE sales.customer (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(200) NOT NULL UNIQUE,
    first_name    varchar(100) NOT NULL,
    last_name     varchar(100) NOT NULL,
    country_code  char(2)      NOT NULL,
    status        varchar(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
    created_at    timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  sales.customer              IS 'Retail customers (one row per account)';
COMMENT ON COLUMN sales.customer.email        IS 'Login / contact e-mail, unique (PII)';
COMMENT ON COLUMN sales.customer.country_code IS 'ISO 3166-1 alpha-2 country of residence';

CREATE TABLE sales.product (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           varchar(40)   NOT NULL UNIQUE,
    name          varchar(200)  NOT NULL,
    category      varchar(60)   NOT NULL,
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    active        smallint      NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at    timestamptz   NOT NULL DEFAULT now()
);
COMMENT ON TABLE sales.product IS 'Sellable products (catalogue)';

CREATE SEQUENCE sales.order_no_seq START WITH 100000 INCREMENT BY 1 CACHE 100;

CREATE TABLE sales.orders (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no      varchar(20)   NOT NULL UNIQUE,
    customer_id   bigint        NOT NULL REFERENCES sales.customer (id),
    order_date    timestamptz   NOT NULL DEFAULT now(),
    status        varchar(20)   NOT NULL DEFAULT 'NEW'
                  CHECK (status IN ('NEW', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    currency_code char(3)       NOT NULL DEFAULT 'EUR',
    total_amount  numeric(14,2) NOT NULL DEFAULT 0,
    updated_at    timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX orders_customer_ix ON sales.orders (customer_id);
CREATE INDEX orders_date_ix     ON sales.orders (order_date);
CREATE INDEX orders_status_ix   ON sales.orders (status);
COMMENT ON TABLE sales.orders IS 'Customer orders (header)';

CREATE TABLE sales.order_item (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint        NOT NULL REFERENCES sales.orders (id) ON DELETE CASCADE,
    product_id    bigint        NOT NULL REFERENCES sales.product (id),
    qty           integer       NOT NULL CHECK (qty > 0),
    unit_price    numeric(12,2) NOT NULL,
    line_total    numeric(14,2) NOT NULL,
    UNIQUE (order_id, product_id)
);
CREATE INDEX order_item_product_ix ON sales.order_item (product_id);
COMMENT ON TABLE sales.order_item IS 'Order lines';

CREATE TABLE sales.inventory (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     bigint      NOT NULL REFERENCES sales.product (id),
    warehouse_code varchar(10) NOT NULL DEFAULT 'MAIN',
    qty_on_hand    integer     NOT NULL DEFAULT 0,
    qty_reserved   integer     NOT NULL DEFAULT 0,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (product_id, warehouse_code),
    CHECK (qty_on_hand >= 0 AND qty_reserved >= 0)
);
COMMENT ON TABLE sales.inventory IS 'Stock levels per product and warehouse';

CREATE TABLE sales.payment (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint        NOT NULL REFERENCES sales.orders (id),
    amount        numeric(14,2) NOT NULL,
    method        varchar(20)   NOT NULL CHECK (method IN ('CARD', 'TRANSFER', 'WALLET', 'INVOICE')),
    status        varchar(20)   NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'CAPTURED', 'REFUNDED', 'FAILED')),
    paid_at       timestamptz,
    created_at    timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX payment_order_ix ON sales.payment (order_id);
CREATE INDEX payment_paid_ix  ON sales.payment (paid_at);
COMMENT ON TABLE sales.payment IS 'Payments and refunds against orders';

CREATE TABLE sales.audit_log (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name     varchar(30)  NOT NULL,
    row_id         bigint       NOT NULL,
    action         varchar(10)  NOT NULL,
    old_status     varchar(20),
    new_status     varchar(20),
    changed_by     varchar(128) NOT NULL,
    client_program varchar(128),
    client_module  varchar(128),
    changed_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_changed_ix ON sales.audit_log (changed_at);
CREATE INDEX audit_log_row_ix     ON sales.audit_log (table_name, row_id);
COMMENT ON TABLE sales.audit_log IS 'Row-level change log written by triggers';

CREATE OR REPLACE VIEW sales.v_customer_order_summary AS
SELECT c.id                           AS customer_id,
       c.email,
       c.country_code,
       count(o.id)                    AS order_count,
       coalesce(sum(o.total_amount), 0) AS lifetime_value,
       max(o.order_date)              AS last_order_date
  FROM sales.customer c
  LEFT JOIN sales.orders o ON o.customer_id = c.id AND o.status <> 'CANCELLED'
 GROUP BY c.id, c.email, c.country_code;

RESET ROLE;
