{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbp.secretName" . }}
  labels:
    {{- include "dbp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DBP_SERVICE_TOKEN: {{ .Values.secrets.serviceToken | quote }}
  DBP_MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  DBP_DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
