package org.dbplatform.jdbc;

import org.dbplatform.protocol.ProtocolConstants;
import org.dbplatform.protocol.TypedNull;
import org.dbplatform.protocol.messages.CloseStatement;
import org.dbplatform.protocol.messages.Execute;
import org.dbplatform.protocol.messages.Execute.Expect;
import org.dbplatform.protocol.messages.Execute.OutParam;
import org.dbplatform.protocol.messages.ExecuteBatch;
import org.dbplatform.protocol.messages.Message;
import org.dbplatform.protocol.messages.Prepare;
import org.dbplatform.protocol.messages.Prepared;
import org.dbplatform.protocol.messages.StatementKind;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;

/**
 * {@link PreparedStatement}: the SQL is registered with PREPARE lazily at the first execution (the gateway
 * does not touch the physical database for that) and executed by {@code statementId}. If the gateway reports
 * the statement id as unknown (SQLState {@code HY000}, message mentioning an unknown statement) the statement
 * is re-prepared transparently once.
 *
 * <p>{@code getMetaData()} executes nothing: it returns the metadata of the current result set, or
 * {@code null} when no result set exists yet (the protocol carries result-set metadata only with results).</p>
 */
public class DbpPreparedStatement extends DbpStatement implements PreparedStatement {

    private static final Object UNSET = new Object();
    private static final String STATE_PARAMETER_NOT_SET = "07001";

    protected final String sql;
    protected final StatementKind kind;
    private final int autoGeneratedKeys;
    private final List<String> generatedKeyColumns;
    private final ArrayList<Object> params = new ArrayList<>();
    private final List<List<Object>> paramBatch = new ArrayList<>();

    private int statementId = ProtocolConstants.DIRECT_STATEMENT_ID;
    private int parameterCount = ProtocolConstants.UNKNOWN_PARAMETER_COUNT;

    DbpPreparedStatement(DbpConnection connection, String sql, StatementKind kind, int resultSetType,
                         int resultSetConcurrency, int resultSetHoldability, int autoGeneratedKeys,
                         List<String> generatedKeyColumns) throws SQLException {
        super(connection, resultSetType, resultSetConcurrency, resultSetHoldability);
        if (sql == null) {
            throw DbpSqlExceptions.invalidArgument("sql must not be null");
        }
        this.sql = sql;
        this.kind = kind;
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.generatedKeyColumns = generatedKeyColumns == null ? List.of() : List.copyOf(generatedKeyColumns);
    }

    /** The SQL text this statement was created with. */
    public String getSql() {
        return sql;
    }

    int statementId() {
        return statementId;
    }

    // ---------------------------------------------------------------- prepare / execute

    protected final void ensurePrepared() throws SQLException {
        checkOpen();
        if (statementId != ProtocolConstants.DIRECT_STATEMENT_ID) {
            return;
        }
        Message m = connection.exchangeTerminal(new Prepare(sql, kind, autoGeneratedKeys, generatedKeyColumns));
        if (!(m instanceof Prepared p)) {
            throw DbpSqlExceptions.protocolViolation("expected PREPARED but got " + m.type());
        }
        statementId = p.statementId();
        parameterCount = p.parameterCount();
    }

    /** Hook: OUT parameter registrations (callable statements). */
    protected List<OutParam> outParams() {
        return List.of();
    }

    /** Hook: whether an unbound parameter slot is acceptable (registered OUT parameter). */
    protected boolean allowsUnset(int index) {
        return false;
    }

    /** Hook: number of parameter slots to send. */
    protected int parameterSlotCount() {
        return Math.max(params.size(), parameterCount);
    }

    protected final List<Object> snapshotParams() throws SQLException {
        int n = parameterSlotCount();
        List<Object> out = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            Object v = i < params.size() ? params.get(i) : UNSET;
            if (v == UNSET) {
                if (!allowsUnset(i + 1)) {
                    throw new SQLException("parameter " + (i + 1) + " is not set", STATE_PARAMETER_NOT_SET);
                }
                v = null;
            }
            out.add(v);
        }
        return out;
    }

    private ExecutionResult executePrepared(Expect expect) throws SQLException {
        ensurePrepared();
        List<Object> p = snapshotParams();
        try {
            return executeAndInstall(new Execute(statementId, null, kind, p,
                    options(expect, autoGeneratedKeys, generatedKeyColumns), outParams()));
        } catch (SQLException e) {
            if (!isUnknownStatement(e)) {
                throw e;
            }
            statementId = ProtocolConstants.DIRECT_STATEMENT_ID;
            ensurePrepared();
            return executeAndInstall(new Execute(statementId, null, kind, p,
                    options(expect, autoGeneratedKeys, generatedKeyColumns), outParams()));
        }
    }

    /**
     * Heuristic for "the gateway lost my statement id": SQLState {@code HY000} with a message mentioning an
     * unknown / not found / no such statement. The gateway is expected to phrase such errors that way.
     */
    static boolean isUnknownStatement(SQLException e) {
        if (!"HY000".equals(e.getSQLState()) || e.getMessage() == null) {
            return false;
        }
        String m = e.getMessage().toLowerCase(Locale.ROOT);
        return m.contains("statement") && (m.contains("unknown") || m.contains("not found") || m.contains("no such")
                || m.contains("invalid statement"));
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        executePrepared(Expect.QUERY);
        return requireResultSet();
    }

    @Override
    public int executeUpdate() throws SQLException {
        long n = executeLargeUpdate();
        return n > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) n;
    }

    @Override
    public long executeLargeUpdate() throws SQLException {
        executePrepared(Expect.UPDATE);
        return requireUpdateCount();
    }

    @Override
    public boolean execute() throws SQLException {
        executePrepared(Expect.ANY);
        return currentResultSet() != null;
    }

    private static SQLException noSqlOnPrepared() {
        return new SQLException("SQL text cannot be passed to a PreparedStatement; use the parameterless execute methods",
                DbpSqlExceptions.STATE_SEQUENCE_ERROR);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        throw noSqlOnPrepared();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        throw noSqlOnPrepared();
    }

    // ---------------------------------------------------------------- batch

    @Override
    public void addBatch() throws SQLException {
        checkOpen();
        paramBatch.add(snapshotParams());
    }

    @Override
    public void clearBatch() throws SQLException {
        super.clearBatch();
        paramBatch.clear();
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        checkOpen();
        if (paramBatch.isEmpty()) {
            return new long[0];
        }
        try {
            ensurePrepared();
            List<List<Object>> sets = new ArrayList<>(paramBatch);
            try {
                return runBatch(ExecuteBatch.ofPrepared(statementId, kind, sets));
            } catch (SQLException e) {
                SQLException cause = e.getCause() instanceof SQLException c ? c : e;
                if (!isUnknownStatement(cause)) {
                    throw e;
                }
                statementId = ProtocolConstants.DIRECT_STATEMENT_ID;
                ensurePrepared();
                return runBatch(ExecuteBatch.ofPrepared(statementId, kind, sets));
            }
        } finally {
            paramBatch.clear();
        }
    }

    // ---------------------------------------------------------------- metadata

    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        checkOpen();
        DbpResultSet rs = currentResultSet();
        return rs == null || rs.isClosed() ? null : rs.getMetaData();
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        ensurePrepared();
        return new DbpParameterMetaData(parameterCount >= 0 ? parameterCount : params.size());
    }

    @Override
    protected void closeRemote() throws SQLException {
        if (statementId != ProtocolConstants.DIRECT_STATEMENT_ID) {
            int id = statementId;
            statementId = ProtocolConstants.DIRECT_STATEMENT_ID;
            connection.exchangeOk(new CloseStatement(id));
        }
    }

    // ---------------------------------------------------------------- parameters

    protected final void setParam(int index, Object value) throws SQLException {
        checkOpen();
        if (index < 1) {
            throw DbpSqlExceptions.invalidIndex("parameter index " + index + " must be >= 1");
        }
        if (parameterCount >= 0 && index > parameterCount) {
            throw DbpSqlExceptions.invalidIndex("parameter index " + index + " out of range 1.." + parameterCount);
        }
        while (params.size() < index) {
            params.add(UNSET);
        }
        params.set(index - 1, value);
    }

    private static Object orTypedNull(Object value, int jdbcType) {
        return value == null ? new TypedNull(jdbcType) : value;
    }

    @Override
    public void clearParameters() throws SQLException {
        checkOpen();
        params.clear();
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        setParam(parameterIndex, new TypedNull(sqlType));
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        setParam(parameterIndex, new TypedNull(sqlType));
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        setParam(parameterIndex, x);
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        setParam(parameterIndex, orTypedNull(x, Types.DECIMAL));
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {
        setParam(parameterIndex, orTypedNull(x, Types.VARCHAR));
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        setParam(parameterIndex, orTypedNull(value, Types.NVARCHAR));
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        setParam(parameterIndex, x == null ? new TypedNull(Types.VARBINARY) : x.clone());
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException {
        setDate(parameterIndex, x, null);
    }

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        if (x == null) {
            setParam(parameterIndex, new TypedNull(Types.DATE));
            return;
        }
        LocalDate d = cal == null ? x.toLocalDate()
                : Instant.ofEpochMilli(x.getTime()).atZone(cal.getTimeZone().toZoneId()).toLocalDate();
        setParam(parameterIndex, d);
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        setTime(parameterIndex, x, null);
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        if (x == null) {
            setParam(parameterIndex, new TypedNull(Types.TIME));
            return;
        }
        ZoneId zone = cal == null ? ZoneId.systemDefault() : cal.getTimeZone().toZoneId();
        LocalTime t = Instant.ofEpochMilli(x.getTime()).atZone(zone).toLocalTime();
        setParam(parameterIndex, t);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        setTimestamp(parameterIndex, x, null);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        if (x == null) {
            setParam(parameterIndex, new TypedNull(Types.TIMESTAMP));
            return;
        }
        LocalDateTime ldt = cal == null ? x.toLocalDateTime()
                : LocalDateTime.ofInstant(x.toInstant(), cal.getTimeZone().toZoneId());
        setParam(parameterIndex, ldt);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        setAsciiStream(parameterIndex, x, (long) length);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readAscii(x, length), Types.LONGVARCHAR));
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        setAsciiStream(parameterIndex, x, -1L);
    }

    @Override
    @Deprecated
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        byte[] b = Conversions.readFully(x, length);
        setParam(parameterIndex, b == null ? new TypedNull(Types.LONGVARCHAR) : new String(b, StandardCharsets.UTF_8));
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        setBinaryStream(parameterIndex, x, (long) length);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(x, length), Types.LONGVARBINARY));
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        setBinaryStream(parameterIndex, x, -1L);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        setCharacterStream(parameterIndex, reader, (long) length);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(reader, length), Types.LONGVARCHAR));
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        setCharacterStream(parameterIndex, reader, -1L);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(value, length), Types.LONGNVARCHAR));
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        setNCharacterStream(parameterIndex, value, -1L);
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readBlob(x), Types.BLOB));
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(inputStream, length), Types.BLOB));
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        setBlob(parameterIndex, inputStream, -1L);
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readClob(x), Types.CLOB));
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(reader, length), Types.CLOB));
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        setClob(parameterIndex, reader, -1L);
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readClob(value), Types.NCLOB));
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        setParam(parameterIndex, orTypedNull(Conversions.readFully(reader, length), Types.NCLOB));
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        setNClob(parameterIndex, reader, -1L);
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        setParam(parameterIndex, orTypedNull(x == null ? null : x.toString(), Types.DATALINK));
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {
        setParam(parameterIndex, Conversions.toParameter(x));
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        setParam(parameterIndex, Conversions.toParameter(x, targetSqlType, null));
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        Integer scale = (targetSqlType == Types.NUMERIC || targetSqlType == Types.DECIMAL) ? scaleOrLength : null;
        setParam(parameterIndex, Conversions.toParameter(x, targetSqlType, scale));
    }

    @Override
    public void setObject(int parameterIndex, Object x, SQLType targetSqlType) throws SQLException {
        setObject(parameterIndex, x, vendorType(targetSqlType));
    }

    @Override
    public void setObject(int parameterIndex, Object x, SQLType targetSqlType, int scaleOrLength) throws SQLException {
        setObject(parameterIndex, x, vendorType(targetSqlType), scaleOrLength);
    }

    static int vendorType(SQLType type) throws SQLException {
        if (type == null || type.getVendorTypeNumber() == null) {
            throw DbpSqlExceptions.invalidArgument("SQLType without a vendor type number");
        }
        return type.getVendorTypeNumber();
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        throw notSupported("setRef");
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        throw notSupported("setArray (ARRAY parameters)");
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        throw notSupported("setRowId");
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        throw notSupported("setSQLXML (pass XML as a String)");
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "[" + (isClosed() ? "closed" : "open") + ", statementId=" + statementId + "]";
    }
}
