package org.dbplatform.jdbc;

import org.dbplatform.protocol.ColumnMeta;
import org.dbplatform.protocol.messages.BatchResult;
import org.dbplatform.protocol.messages.Execute;
import org.dbplatform.protocol.messages.Execute.ExecOptions;
import org.dbplatform.protocol.messages.Execute.Expect;
import org.dbplatform.protocol.messages.ExecuteBatch;
import org.dbplatform.protocol.messages.GeneratedKeys;
import org.dbplatform.protocol.messages.Message;
import org.dbplatform.protocol.messages.StatementKind;

import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * {@link Statement} executing direct SQL through EXECUTE ({@code statementId = -1}, {@code kind = STATEMENT}).
 * Also the base class of the prepared and callable statements: it owns the ordered result items of the last
 * execution ({@code getResultSet} / {@code getUpdateCount} / {@code getMoreResults}), generated keys,
 * warnings, the open result sets and the statement batch.
 *
 * <p>{@code cancel()} is a documented no-op that only records a warning: the protocol is strictly synchronous
 * on one socket, so there is no out-of-band channel to reach the gateway while an EXECUTE is in flight. Use
 * {@code setQueryTimeout} (the gateway answers {@code HY008}).</p>
 */
public class DbpStatement extends DbpWrapper implements Statement {

    private static final String STATE_CANCEL_IGNORED = "01000";
    private static final String STATE_GENERAL_WARNING = "01000";

    protected final DbpConnection connection;
    protected final DbpWarningChain warnings = new DbpWarningChain();
    private final int resultSetType;
    private final int resultSetConcurrency;
    private final int resultSetHoldability;
    private final Set<DbpResultSet> openResultSets = new LinkedHashSet<>();
    private final List<String> batch = new ArrayList<>();

    private int fetchSize;
    private long maxRows;
    private int maxFieldSize;
    private int queryTimeout;
    private boolean poolable;
    private boolean closeOnCompletion;
    private volatile boolean closed;
    private boolean installing;

    private List<ExecutionResult.Item> items = List.of();
    private int itemIndex = -1;
    private DbpResultSet currentResultSet;
    private long currentUpdateCount = -1;
    private GeneratedKeys generatedKeys;

    DbpStatement(DbpConnection connection, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        this.connection = connection;
        this.resultSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = resultSetHoldability;
        this.fetchSize = connection.defaultFetchSize();
        this.poolable = this instanceof DbpPreparedStatement;
    }

    // ---------------------------------------------------------------- execution core

    protected final void checkOpen() throws SQLException {
        if (closed) {
            throw DbpSqlExceptions.statementClosed();
        }
        if (connection.isClosed()) {
            closed = true;
            throw DbpSqlExceptions.connectionClosed();
        }
    }

    protected final ExecOptions options(Expect expect, int autoGeneratedKeys, List<String> generatedKeyColumns) {
        return new ExecOptions((int) Math.min(Integer.MAX_VALUE, maxRows), fetchSize, queryTimeout, expect,
                autoGeneratedKeys, generatedKeyColumns == null ? List.of() : generatedKeyColumns);
    }

    /** Sends an EXECUTE (or METADATA) request and installs its result items as the current results. */
    protected final ExecutionResult executeAndInstall(Message request) throws SQLException {
        checkOpen();
        List<Message> replies = connection.exchange(request, -1);
        ExecutionResult result = ExecutionResult.parse(replies);
        install(result);
        return result;
    }

    private void install(ExecutionResult result) throws SQLException {
        installing = true;
        try {
            // the EXECUTE already succeeded: a failure while closing the previous result sets (e.g. the gateway rejecting
            // a CLOSE_CURSOR) must not discard the new results; it is attached as a warning instead
            SQLException closeFailure = closeAllResultSetsQuietly();
            generatedKeys = result.generatedKeys;
            warnings.addAll(result.warnings);
            if (closeFailure != null) {
                warnings.add(previousResultsWarning(closeFailure));
            }
            items = filterItems(result);
            itemIndex = -1;
            advance();
        } finally {
            installing = false;
        }
    }

    private static SQLWarning previousResultsWarning(SQLException cause) {
        return new SQLWarning("a previous result set of this statement could not be closed: " + cause.getMessage(),
                STATE_GENERAL_WARNING, cause.getErrorCode(), cause);
    }

    /** Hook for subclasses to remove result items that are not navigable (cursor-typed OUT parameters). */
    protected List<ExecutionResult.Item> filterItems(ExecutionResult result) throws SQLException {
        return result.items;
    }

    private void advance() {
        itemIndex++;
        if (itemIndex < items.size()) {
            ExecutionResult.Item item = items.get(itemIndex);
            if (item instanceof ExecutionResult.ResultSetItem rs) {
                currentResultSet = newResultSet(rs);
                currentUpdateCount = -1;
            } else {
                currentResultSet = null;
                currentUpdateCount = ((ExecutionResult.UpdateCountItem) item).count();
            }
        } else {
            currentResultSet = null;
            currentUpdateCount = -1;
        }
    }

    protected final DbpResultSet newResultSet(ExecutionResult.ResultSetItem item) {
        DbpResultSet rs = new DbpResultSet(connection, this, item.cursorId(), item.header().columns(),
                item.rows().rows(), item.rows().last(), fetchSize, maxRows);
        synchronized (openResultSets) {
            openResultSets.add(rs);
        }
        return rs;
    }

    private void closeAllResultSets() throws SQLException {
        SQLException first = closeAllResultSetsQuietly();
        if (first != null) {
            throw first;
        }
    }

    /** Closes every open result set (best effort) and returns the first failure, with the others chained, or null. */
    private SQLException closeAllResultSetsQuietly() {
        List<DbpResultSet> toClose;
        synchronized (openResultSets) {
            toClose = new ArrayList<>(openResultSets);
        }
        SQLException first = null;
        for (DbpResultSet rs : toClose) {
            try {
                rs.close();
            } catch (SQLException e) {
                if (first == null) {
                    first = e;
                } else {
                    first.setNextException(e);
                }
            }
        }
        return first;
    }

    /** Called by a result set when it closes. */
    void resultSetClosed(DbpResultSet rs) {
        boolean empty;
        synchronized (openResultSets) {
            openResultSets.remove(rs);
            empty = openResultSets.isEmpty();
        }
        if (closeOnCompletion && empty && !installing && !closed) {
            try {
                close();
            } catch (SQLException ignored) {
                // best effort
            }
        }
    }

    protected final DbpResultSet currentResultSet() {
        return currentResultSet;
    }

    protected final long currentUpdateCount() {
        return currentUpdateCount;
    }

    private static int clampToInt(long count) {
        return count > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) count;
    }

    // ---------------------------------------------------------------- direct SQL

    private Execute direct(String sql, Expect expect, int autoGeneratedKeys, List<String> keyColumns) throws SQLException {
        if (sql == null) {
            throw DbpSqlExceptions.invalidArgument("sql must not be null");
        }
        return Execute.direct(sql, StatementKind.STATEMENT, List.of(), options(expect, autoGeneratedKeys, keyColumns));
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        executeAndInstall(direct(sql, Expect.QUERY, NO_GENERATED_KEYS, List.of()));
        return requireResultSet();
    }

    protected final ResultSet requireResultSet() throws SQLException {
        if (currentResultSet == null) {
            throw DbpSqlExceptions.wrongResultShape("the statement did not produce a result set");
        }
        return currentResultSet;
    }

    protected final long requireUpdateCount() throws SQLException {
        if (currentResultSet != null) {
            throw DbpSqlExceptions.wrongResultShape("the statement produced a result set");
        }
        return Math.max(0, currentUpdateCount);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return clampToInt(executeLargeUpdate(sql));
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        executeAndInstall(direct(sql, Expect.UPDATE, NO_GENERATED_KEYS, List.of()));
        return requireUpdateCount();
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        executeAndInstall(direct(sql, Expect.ANY, NO_GENERATED_KEYS, List.of()));
        return currentResultSet != null;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return clampToInt(executeLargeUpdate(sql, autoGeneratedKeys));
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        executeAndInstall(direct(sql, Expect.UPDATE, checkKeysFlag(autoGeneratedKeys), List.of()));
        return requireUpdateCount();
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw notSupported("generated key column indexes (use column names)");
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw notSupported("generated key column indexes (use column names)");
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return clampToInt(executeLargeUpdate(sql, columnNames));
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        executeAndInstall(direct(sql, Expect.UPDATE, RETURN_GENERATED_KEYS, keyColumns(columnNames)));
        return requireUpdateCount();
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        executeAndInstall(direct(sql, Expect.ANY, checkKeysFlag(autoGeneratedKeys), List.of()));
        return currentResultSet != null;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw notSupported("generated key column indexes (use column names)");
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        executeAndInstall(direct(sql, Expect.ANY, RETURN_GENERATED_KEYS, keyColumns(columnNames)));
        return currentResultSet != null;
    }

    static int checkKeysFlag(int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != RETURN_GENERATED_KEYS && autoGeneratedKeys != NO_GENERATED_KEYS) {
            throw DbpSqlExceptions.invalidArgument("invalid autoGeneratedKeys flag " + autoGeneratedKeys);
        }
        return autoGeneratedKeys;
    }

    static List<String> keyColumns(String[] columnNames) throws SQLException {
        if (columnNames == null) {
            return List.of();
        }
        List<String> l = new ArrayList<>(columnNames.length);
        for (String c : columnNames) {
            if (c == null) {
                throw DbpSqlExceptions.invalidArgument("generated key column name must not be null");
            }
            l.add(c);
        }
        return l;
    }

    // ---------------------------------------------------------------- results

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkOpen();
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        checkOpen();
        return currentUpdateCount < 0 ? -1 : clampToInt(currentUpdateCount);
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        checkOpen();
        return currentUpdateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(CLOSE_CURRENT_RESULT);
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        checkOpen();
        switch (current) {
            case CLOSE_CURRENT_RESULT -> {
                if (currentResultSet != null) {
                    currentResultSet.close();
                }
            }
            case CLOSE_ALL_RESULTS -> closeAllResultSets();
            case KEEP_CURRENT_RESULT -> {
                // keep
            }
            default -> throw DbpSqlExceptions.invalidArgument("invalid getMoreResults flag " + current);
        }
        if (itemIndex >= items.size()) {
            currentResultSet = null;
            currentUpdateCount = -1;
            return false;
        }
        advance();
        return currentResultSet != null;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkOpen();
        DbpResultSet rs;
        if (generatedKeys == null) {
            rs = DbpResultSet.inMemory(connection, this, List.<ColumnMeta>of(), List.of());
        } else {
            rs = DbpResultSet.inMemory(connection, this, generatedKeys.columns(), generatedKeys.rows());
        }
        synchronized (openResultSets) {
            openResultSets.add(rs);
        }
        return rs;
    }

    // ---------------------------------------------------------------- batch

    @Override
    public void addBatch(String sql) throws SQLException {
        checkOpen();
        if (sql == null) {
            throw DbpSqlExceptions.invalidArgument("sql must not be null");
        }
        batch.add(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        checkOpen();
        batch.clear();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        return toIntCounts(executeLargeBatch());
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        checkOpen();
        if (batch.isEmpty()) {
            return new long[0];
        }
        try {
            return runBatch(ExecuteBatch.ofStatements(batch));
        } finally {
            batch.clear();
        }
    }

    /** Sends an EXECUTE_BATCH and returns its counts; failures become {@link BatchUpdateException}. */
    protected final long[] runBatch(ExecuteBatch request) throws SQLException {
        installing = true;
        SQLException closeFailure;
        try {
            closeFailure = closeAllResultSetsQuietly();
        } finally {
            installing = false;
        }
        if (closeFailure != null) {
            warnings.add(previousResultsWarning(closeFailure)); // best effort: the batch itself still runs
        }
        items = List.of();
        itemIndex = 0;
        currentResultSet = null;
        currentUpdateCount = -1;
        generatedKeys = null;
        Message terminal;
        try {
            terminal = connection.exchangeTerminal(request);
        } catch (BatchUpdateException e) {
            throw e;
        } catch (SQLException e) {
            BatchUpdateException bue = new BatchUpdateException(e.getMessage(), e.getSQLState(), e.getErrorCode(),
                    new long[0], e);
            bue.setNextException(e.getNextException());
            throw bue;
        }
        if (!(terminal instanceof BatchResult result)) {
            throw DbpSqlExceptions.protocolViolation("expected BATCH_RESULT but got " + terminal.type());
        }
        warnings.addAll(result.warnings());
        return result.updateCounts();
    }

    static int[] toIntCounts(long[] counts) {
        int[] out = new int[counts.length];
        for (int i = 0; i < counts.length; i++) {
            long v = counts[i];
            out[i] = (v > Integer.MAX_VALUE || v < Integer.MIN_VALUE) ? SUCCESS_NO_INFO : (int) v;
        }
        return out;
    }

    // ---------------------------------------------------------------- lifecycle

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        closed = true;
        try {
            if (!connection.isClosed()) {
                try {
                    closeAllResultSets();
                } finally {
                    closeRemote();
                }
            } else {
                closeLocally();
            }
        } finally {
            synchronized (openResultSets) {
                openResultSets.clear();
            }
            batch.clear();
            connection.unregisterStatement(this);
        }
    }

    /** Hook: release server-side resources of this statement (CLOSE_STATEMENT for prepared statements). */
    protected void closeRemote() throws SQLException {
        // plain statements hold no server-side state
    }

    /** Marks this statement and its result sets closed without talking to the gateway. */
    void closeLocally() {
        closed = true;
        synchronized (openResultSets) {
            for (DbpResultSet rs : openResultSets) {
                rs.closeLocally();
            }
            openResultSets.clear();
        }
    }

    @Override
    public boolean isClosed() {
        return closed || connection.isClosed();
    }

    @Override
    public void cancel() throws SQLException {
        checkOpen();
        warnings.add("Statement.cancel() is not supported by the DBP JDBC driver (synchronous protocol); "
                + "use setQueryTimeout", STATE_CANCEL_IGNORED);
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        checkOpen();
        closeOnCompletion = true;
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        checkOpen();
        return closeOnCompletion;
    }

    // ---------------------------------------------------------------- properties

    @Override
    public int getMaxFieldSize() throws SQLException {
        checkOpen();
        return maxFieldSize;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        checkOpen();
        if (max < 0) {
            throw DbpSqlExceptions.invalidArgument("max field size must be >= 0");
        }
        maxFieldSize = max;
    }

    @Override
    public int getMaxRows() throws SQLException {
        checkOpen();
        return clampToInt(maxRows);
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        setLargeMaxRows(max);
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        checkOpen();
        return maxRows;
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        checkOpen();
        if (max < 0) {
            throw DbpSqlExceptions.invalidArgument("max rows must be >= 0");
        }
        maxRows = max;
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        checkOpen();
        // escape sequences are forwarded as part of the SQL and processed by the physical driver
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        checkOpen();
        return queryTimeout;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkOpen();
        if (seconds < 0) {
            throw DbpSqlExceptions.invalidArgument("query timeout must be >= 0");
        }
        queryTimeout = seconds;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkOpen();
        return warnings.get();
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkOpen();
        warnings.clear();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        throw notSupported("named cursors");
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        checkOpen();
        if (direction != ResultSet.FETCH_FORWARD) {
            throw DbpSqlExceptions.invalidArgument("only FETCH_FORWARD is supported");
        }
    }

    @Override
    public int getFetchDirection() throws SQLException {
        checkOpen();
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        checkOpen();
        if (rows < 0) {
            throw DbpSqlExceptions.invalidArgument("fetch size must be >= 0");
        }
        fetchSize = rows == 0 ? connection.defaultFetchSize() : rows;
    }

    @Override
    public int getFetchSize() throws SQLException {
        checkOpen();
        return fetchSize;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        checkOpen();
        return resultSetConcurrency;
    }

    @Override
    public int getResultSetType() throws SQLException {
        checkOpen();
        return resultSetType;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        checkOpen();
        return resultSetHoldability;
    }

    @Override
    public Connection getConnection() throws SQLException {
        checkOpen();
        return connection;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        checkOpen();
        this.poolable = poolable;
    }

    @Override
    public boolean isPoolable() throws SQLException {
        checkOpen();
        return poolable;
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "[" + (closed ? "closed" : "open") + "]";
    }
}
