-- =====================================================================================
-- 10_schema.sql  --  Retail demo schema SALES (Oracle Database Free 23)
--
-- Tables: CUSTOMER, PRODUCT, ORDERS, ORDER_ITEM, INVENTORY, PAYMENT, AUDIT_LOG
-- plus the reporting view V_CUSTOMER_ORDER_SUMMARY.
-- Identity columns generate surrogate keys; ORDERS additionally has a human readable
-- ORDER_NO fed by sequence ORDER_NO_SEQ (so the demo exercises both mechanisms).
-- =====================================================================================
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SALES;

-- ---------------------------------------------------------------------------
-- CUSTOMER
-- ---------------------------------------------------------------------------
CREATE TABLE CUSTOMER (
    ID            NUMBER(12)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    EMAIL         VARCHAR2(200)   NOT NULL,
    FIRST_NAME    VARCHAR2(100)   NOT NULL,
    LAST_NAME     VARCHAR2(100)   NOT NULL,
    COUNTRY_CODE  CHAR(2)         NOT NULL,
    STATUS        VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT    TIMESTAMP(3)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CUSTOMER_PK  PRIMARY KEY (ID),
    CONSTRAINT CUSTOMER_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT CUSTOMER_STATUS_CK CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);
COMMENT ON TABLE  CUSTOMER              IS 'Retail customers (one row per account)';
COMMENT ON COLUMN CUSTOMER.EMAIL        IS 'Login / contact e-mail, unique (PII)';
COMMENT ON COLUMN CUSTOMER.COUNTRY_CODE IS 'ISO 3166-1 alpha-2 country of residence';
COMMENT ON COLUMN CUSTOMER.STATUS       IS 'ACTIVE, BLOCKED or CLOSED';

-- ---------------------------------------------------------------------------
-- PRODUCT
-- ---------------------------------------------------------------------------
CREATE TABLE PRODUCT (
    ID            NUMBER(12)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    SKU           VARCHAR2(40)    NOT NULL,
    NAME          VARCHAR2(200)   NOT NULL,
    CATEGORY      VARCHAR2(60)    NOT NULL,
    UNIT_PRICE    NUMBER(12,2)    NOT NULL,
    ACTIVE        NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP(3)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
    CONSTRAINT PRODUCT_SKU_UK UNIQUE (SKU),
    CONSTRAINT PRODUCT_PRICE_CK CHECK (UNIT_PRICE >= 0),
    CONSTRAINT PRODUCT_ACTIVE_CK CHECK (ACTIVE IN (0, 1))
);
COMMENT ON TABLE  PRODUCT            IS 'Sellable products (catalogue)';
COMMENT ON COLUMN PRODUCT.SKU        IS 'Stock keeping unit, unique';
COMMENT ON COLUMN PRODUCT.UNIT_PRICE IS 'List price per unit, before discounts';

-- ---------------------------------------------------------------------------
-- ORDERS  (ORDER is a reserved word)
-- ---------------------------------------------------------------------------
CREATE SEQUENCE ORDER_NO_SEQ START WITH 100000 INCREMENT BY 1 CACHE 100 NOCYCLE;

CREATE TABLE ORDERS (
    ID            NUMBER(12)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_NO      VARCHAR2(20)    NOT NULL,
    CUSTOMER_ID   NUMBER(12)      NOT NULL,
    ORDER_DATE    TIMESTAMP(3)    DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS        VARCHAR2(20)    DEFAULT 'NEW' NOT NULL,
    CURRENCY_CODE CHAR(3)         DEFAULT 'EUR' NOT NULL,
    TOTAL_AMOUNT  NUMBER(14,2)    DEFAULT 0 NOT NULL,
    UPDATED_AT    TIMESTAMP(3)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ORDERS_PK PRIMARY KEY (ID),
    CONSTRAINT ORDERS_NO_UK UNIQUE (ORDER_NO),
    CONSTRAINT ORDERS_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
    CONSTRAINT ORDERS_STATUS_CK CHECK (STATUS IN ('NEW', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);
CREATE INDEX ORDERS_CUSTOMER_IX ON ORDERS (CUSTOMER_ID);
CREATE INDEX ORDERS_DATE_IX     ON ORDERS (ORDER_DATE);
CREATE INDEX ORDERS_STATUS_IX   ON ORDERS (STATUS);
COMMENT ON TABLE  ORDERS              IS 'Customer orders (header)';
COMMENT ON COLUMN ORDERS.ORDER_NO     IS 'Human readable order number from ORDER_NO_SEQ';
COMMENT ON COLUMN ORDERS.STATUS       IS 'NEW -> PAID -> SHIPPED -> DELIVERED, or CANCELLED';
COMMENT ON COLUMN ORDERS.TOTAL_AMOUNT IS 'Sum of ORDER_ITEM.LINE_TOTAL after tier discount';

-- ---------------------------------------------------------------------------
-- ORDER_ITEM
-- ---------------------------------------------------------------------------
CREATE TABLE ORDER_ITEM (
    ID            NUMBER(12)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_ID      NUMBER(12)      NOT NULL,
    PRODUCT_ID    NUMBER(12)      NOT NULL,
    QTY           NUMBER(8)       NOT NULL,
    UNIT_PRICE    NUMBER(12,2)    NOT NULL,
    LINE_TOTAL    NUMBER(14,2)    NOT NULL,
    CONSTRAINT ORDER_ITEM_PK PRIMARY KEY (ID),
    CONSTRAINT ORDER_ITEM_ORDER_FK   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS (ID) ON DELETE CASCADE,
    CONSTRAINT ORDER_ITEM_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT ORDER_ITEM_ORDER_PRODUCT_UK UNIQUE (ORDER_ID, PRODUCT_ID),
    CONSTRAINT ORDER_ITEM_QTY_CK CHECK (QTY > 0)
);
CREATE INDEX ORDER_ITEM_PRODUCT_IX ON ORDER_ITEM (PRODUCT_ID);
COMMENT ON TABLE  ORDER_ITEM            IS 'Order lines';
COMMENT ON COLUMN ORDER_ITEM.UNIT_PRICE IS 'Price at order time (copied from PRODUCT)';

-- ---------------------------------------------------------------------------
-- INVENTORY  (one row per product, single warehouse in the demo)
-- ---------------------------------------------------------------------------
CREATE TABLE INVENTORY (
    ID             NUMBER(12)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PRODUCT_ID     NUMBER(12)     NOT NULL,
    WAREHOUSE_CODE VARCHAR2(10)   DEFAULT 'MAIN' NOT NULL,
    QTY_ON_HAND    NUMBER(10)     DEFAULT 0 NOT NULL,
    QTY_RESERVED   NUMBER(10)     DEFAULT 0 NOT NULL,
    UPDATED_AT     TIMESTAMP(3)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT INVENTORY_PK PRIMARY KEY (ID),
    CONSTRAINT INVENTORY_PRODUCT_UK UNIQUE (PRODUCT_ID, WAREHOUSE_CODE),
    CONSTRAINT INVENTORY_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT INVENTORY_QTY_CK CHECK (QTY_ON_HAND >= 0 AND QTY_RESERVED >= 0)
);
COMMENT ON TABLE  INVENTORY              IS 'Stock levels per product and warehouse';
COMMENT ON COLUMN INVENTORY.QTY_RESERVED IS 'Units reserved by RESERVE_STOCK but not yet written as order lines';

-- ---------------------------------------------------------------------------
-- PAYMENT
-- ---------------------------------------------------------------------------
CREATE TABLE PAYMENT (
    ID            NUMBER(12)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_ID      NUMBER(12)      NOT NULL,
    AMOUNT        NUMBER(14,2)    NOT NULL,
    METHOD        VARCHAR2(20)    NOT NULL,
    STATUS        VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    PAID_AT       TIMESTAMP(3),
    CREATED_AT    TIMESTAMP(3)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PAYMENT_PK PRIMARY KEY (ID),
    CONSTRAINT PAYMENT_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    CONSTRAINT PAYMENT_METHOD_CK CHECK (METHOD IN ('CARD', 'TRANSFER', 'WALLET', 'INVOICE')),
    CONSTRAINT PAYMENT_STATUS_CK CHECK (STATUS IN ('PENDING', 'CAPTURED', 'REFUNDED', 'FAILED'))
);
CREATE INDEX PAYMENT_ORDER_IX  ON PAYMENT (ORDER_ID);
CREATE INDEX PAYMENT_PAID_IX   ON PAYMENT (PAID_AT);
COMMENT ON TABLE  PAYMENT        IS 'Payments and refunds against orders';
COMMENT ON COLUMN PAYMENT.STATUS IS 'PENDING, CAPTURED, REFUNDED or FAILED';

-- ---------------------------------------------------------------------------
-- AUDIT_LOG  (written by trigger TRG_ORDERS_AUDIT)
-- ---------------------------------------------------------------------------
CREATE TABLE AUDIT_LOG (
    ID             NUMBER(14)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TABLE_NAME     VARCHAR2(30)   NOT NULL,
    ROW_ID         NUMBER(12)     NOT NULL,
    ACTION         VARCHAR2(10)   NOT NULL,
    OLD_STATUS     VARCHAR2(20),
    NEW_STATUS     VARCHAR2(20),
    CHANGED_BY     VARCHAR2(128)  NOT NULL,
    CLIENT_PROGRAM VARCHAR2(128),
    CLIENT_MODULE  VARCHAR2(128),
    CHANGED_AT     TIMESTAMP(3)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT AUDIT_LOG_PK PRIMARY KEY (ID)
);
CREATE INDEX AUDIT_LOG_CHANGED_IX ON AUDIT_LOG (CHANGED_AT);
CREATE INDEX AUDIT_LOG_ROW_IX     ON AUDIT_LOG (TABLE_NAME, ROW_ID);
COMMENT ON TABLE  AUDIT_LOG                IS 'Row-level change log written by triggers';
COMMENT ON COLUMN AUDIT_LOG.CLIENT_PROGRAM IS 'SYS_CONTEXT(USERENV, CLIENT_PROGRAM_NAME) of the writing session';
COMMENT ON COLUMN AUDIT_LOG.CLIENT_MODULE  IS 'SYS_CONTEXT(USERENV, MODULE) of the writing session';

-- ---------------------------------------------------------------------------
-- Reporting view (gives the crawler a VIEW -> TABLE dependency)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_CUSTOMER_ORDER_SUMMARY AS
SELECT c.ID            AS CUSTOMER_ID,
       c.EMAIL,
       c.COUNTRY_CODE,
       COUNT(o.ID)     AS ORDER_COUNT,
       NVL(SUM(o.TOTAL_AMOUNT), 0) AS LIFETIME_VALUE,
       MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
  FROM CUSTOMER c
  LEFT JOIN ORDERS o ON o.CUSTOMER_ID = c.ID AND o.STATUS <> 'CANCELLED'
 GROUP BY c.ID, c.EMAIL, c.COUNTRY_CODE;
COMMENT ON TABLE V_CUSTOMER_ORDER_SUMMARY IS 'Per-customer order count and lifetime value';

EXIT
