package org.dbplatform.gateway.session;

import org.dbplatform.common.controlplane.CredentialMaterial;
import org.dbplatform.common.telemetry.Engine;
import org.dbplatform.gateway.control.AuthException;
import org.dbplatform.gateway.control.Identity;
import org.dbplatform.gateway.control.Resolver;
import org.dbplatform.gateway.control.SessionResolution;
import org.dbplatform.gateway.pool.PhysicalPool;
import org.dbplatform.gateway.pool.PoolManager;
import org.dbplatform.gateway.pool.PoolMode;
import org.dbplatform.gateway.telemetry.GatewayTelemetry;
import org.dbplatform.protocol.messages.ErrorMessage;
import org.dbplatform.protocol.messages.StatementKind;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLNonTransientConnectionException;
import java.sql.SQLRecoverableException;
import java.sql.SQLTransientConnectionException;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.Executor;

/**
 * A logical JDBC connection of an application. Holds the remembered settings, registered statements, open cursors
 * and transaction state, and borrows a physical connection from the pool only while needed:
 *
 * <ul>
 *   <li>first need → borrow, apply remembered settings (incl. autocommit);</li>
 *   <li>{@link PoolMode#TRANSACTION}: release when no transaction is open and no cursor is open — i.e. after an
 *       autocommit statement whose result set is exhausted/closed, or after COMMIT / ROLLBACK (full) once the
 *       cursors are closed;</li>
 *   <li>{@link PoolMode#SESSION}: never release before CLOSE / socket EOF.</li>
 * </ul>
 *
 * <p>Instances are confined to the handler thread; the {@code volatile} fields are read by the admin endpoints.</p>
 */
public final class LogicalSession {

    private static final Logger LOG = LoggerFactory.getLogger(LogicalSession.class);

    /** A physical prepared statement cached while pinned. */
    record CachedStatement(PreparedStatement statement, int autoGeneratedKeys, List<String> keyColumns) {
        boolean matches(int genKeys, List<String> cols) {
            return autoGeneratedKeys == genKeys && keyColumns.equals(cols);
        }
    }

    private final String id;
    private final Resolver resolver;
    private final PoolManager pools;
    private final String datasource;
    private final String apiKey;
    private final String applicationHint;
    private final String user;
    private final Identity identity;
    private final PoolMode poolMode;
    private final boolean grantReadOnly;
    private final String grantKey;
    private final int maxOpenCursors;
    private final Executor networkTimeoutExecutor;
    private final String clientAddress;
    private final long createdAtMillis = System.currentTimeMillis();

    private volatile SessionResolution resolution;
    private volatile PhysicalPool helloPool;

    private final SessionSettings settings = new SessionSettings();
    private final Map<Integer, PreparedEntry> prepared = new HashMap<>();
    private final Map<Integer, CachedStatement> physicalStatements = new HashMap<>();
    private final Map<Integer, Cursor> cursors = new LinkedHashMap<>();
    private final Map<String, Savepoint> savepoints = new HashMap<>();
    private final List<String> appliedClientInfo = new ArrayList<>();

    private Connection physical;
    private PhysicalPool pinnedPool;
    private boolean inTransaction;
    private long pinnedSinceMillis;
    private int nextStatementId = 1;
    private int nextCursorId = 1;
    private int nextSavepointId = 1;

    private volatile boolean pinnedFlag;
    private volatile int openCursorCount;
    private volatile long lastActivityMillis = System.currentTimeMillis();
    private volatile boolean executing;
    private volatile boolean closed;
    private volatile long statements;

    public LogicalSession(String id, SessionResolution resolution, Resolver resolver, PoolManager pools,
                          String apiKey, String applicationHint, String user, int maxOpenCursors,
                          Executor networkTimeoutExecutor, String clientAddress) {
        this.id = id;
        this.resolution = resolution;
        this.resolver = resolver;
        this.pools = pools;
        this.datasource = resolution.datasource().name();
        this.apiKey = apiKey;
        this.applicationHint = applicationHint;
        this.user = user;
        this.identity = resolution.identity();
        this.poolMode = resolution.poolMode();
        this.grantReadOnly = resolution.readOnly();
        this.grantKey = resolution.grantKey();
        this.maxOpenCursors = maxOpenCursors;
        this.networkTimeoutExecutor = networkTimeoutExecutor;
        this.clientAddress = clientAddress;
    }

    // ------------------------------------------------------------------ identity / state views

    public String id() {
        return id;
    }

    public Identity identity() {
        return identity;
    }

    public String datasource() {
        return datasource;
    }

    public PoolMode poolMode() {
        return poolMode;
    }

    public String grantKey() {
        return grantKey;
    }

    public SessionSettings settings() {
        return settings;
    }

    public boolean isPinned() {
        return pinnedFlag;
    }

    public int openCursors() {
        return openCursorCount;
    }

    public boolean isExecuting() {
        return executing;
    }

    public void executing(boolean v) {
        executing = v;
    }

    public boolean isClosed() {
        return closed;
    }

    public boolean inTransaction() {
        return inTransaction;
    }

    public long lastActivityMillis() {
        return lastActivityMillis;
    }

    public long createdAtMillis() {
        return createdAtMillis;
    }

    public long pinnedSinceMillis() {
        return pinnedSinceMillis;
    }

    public long statements() {
        return statements;
    }

    public String clientAddress() {
        return clientAddress;
    }

    public void touch() {
        lastActivityMillis = System.currentTimeMillis();
    }

    /** The pool used to answer HELLO (engine, server properties). */
    public void helloPool(PhysicalPool pool) {
        this.helloPool = pool;
    }

    public PhysicalPool currentPool() {
        return pinnedPool != null ? pinnedPool : helloPool;
    }

    public Engine engine() {
        PhysicalPool p = currentPool();
        return p != null ? p.engine() : resolution.datasource().settings().engineHint();
    }

    public String databaseId() {
        return resolution.datasource().databaseId();
    }

    /** Facts for telemetry events. */
    public GatewayTelemetry.SessionFacts facts() {
        PhysicalPool p = currentPool();
        String schema = settings.schema() != null ? settings.schema() : (p != null ? p.defaultSchema() : null);
        return new GatewayTelemetry.SessionFacts(id, identity.applicationId(), identity.application(), identity.team(),
                datasource, databaseId(), engine(), poolMode.name(), new LinkedHashMap<>(settings.clientInfo()), schema);
    }

    // ------------------------------------------------------------------ pinning

    /** Returns the pinned physical connection, borrowing one when the session has none. */
    public Connection acquire() throws SQLException {
        touch();
        if (physical != null) {
            return physical;
        }
        if (closed) {
            throw new SQLNonTransientConnectionException("session is closed", ErrorMessage.STATE_CONNECTION_FAILURE);
        }
        SessionResolution res = refreshResolution();
        PhysicalPool pool = pools.poolFor(res.datasource().settings(), () -> credentials(res));
        Connection c = pool.borrow();
        try {
            applySettings(c, pool);
        } catch (SQLException e) {
            pool.release(c, false);
            throw e;
        }
        physical = c;
        pinnedPool = pool;
        pinnedSinceMillis = System.currentTimeMillis();
        pinnedFlag = true;
        return c;
    }

    private SessionResolution refreshResolution() {
        try {
            SessionResolution fresh = resolver.resolve(datasource, apiKey, applicationHint, user);
            resolution = fresh;
            return fresh;
        } catch (AuthException e) {
            // keep serving with the last known resolution: a control plane hiccup must not break the data path
            LOG.debug("re-resolution of {} failed ({}), keeping previous resolution", datasource, e.getMessage());
            return resolution;
        }
    }

    private CredentialMaterial credentials(SessionResolution res) throws SQLException {
        try {
            return resolver.credentials(res.datasource());
        } catch (AuthException e) {
            throw new SQLTransientConnectionException(e.getMessage(), e.sqlState(), e);
        }
    }

    private void applySettings(Connection c, PhysicalPool pool) throws SQLException {
        c.setAutoCommit(settings.autoCommit());
        if (settings.transactionIsolation() != SessionSettings.UNSET
                && settings.transactionIsolation() != Connection.TRANSACTION_NONE) {
            c.setTransactionIsolation(settings.transactionIsolation());
        }
        boolean readOnly = grantReadOnly || Boolean.TRUE.equals(settings.readOnly());
        if (readOnly || settings.readOnly() != null) {
            c.setReadOnly(readOnly);
        }
        if (settings.schema() != null) {
            c.setSchema(settings.schema());
        }
        if (settings.catalog() != null) {
            c.setCatalog(settings.catalog());
        }
        appliedClientInfo.clear();
        for (Map.Entry<String, String> e : settings.clientInfo().entrySet()) {
            applyClientInfo(c, pool, e.getKey(), e.getValue());
        }
        if (settings.networkTimeoutMillis() != SessionSettings.UNSET) {
            applyNetworkTimeout(c, settings.networkTimeoutMillis());
        }
    }

    private void applyClientInfo(Connection c, PhysicalPool pool, String name, String value) {
        try {
            c.setClientInfo(name, value);
            appliedClientInfo.add(name);
        } catch (SQLException | RuntimeException e) {
            LOG.trace("setClientInfo({}) not accepted: {}", name, e.toString());
        }
        if (pool.engine() == Engine.ORACLE) {
            String mapped = oracleClientInfoName(name);
            if (mapped != null && !mapped.equals(name)) {
                try {
                    c.setClientInfo(mapped, value);
                    appliedClientInfo.add(mapped);
                } catch (SQLException | RuntimeException e) {
                    LOG.trace("setClientInfo({}) not accepted: {}", mapped, e.toString());
                }
            }
        }
    }

    /** Maps the standard JDBC client info names to Oracle's {@code OCSID.*} keys. */
    static String oracleClientInfoName(String name) {
        return switch (name.toLowerCase(Locale.ROOT)) {
            case "applicationname", "module", "ocsid.module" -> "OCSID.MODULE";
            case "clientuser", "clientid", "client_identifier", "ocsid.clientid" -> "OCSID.CLIENTID";
            case "action", "ocsid.action" -> "OCSID.ACTION";
            default -> null;
        };
    }

    private void applyNetworkTimeout(Connection c, int millis) {
        try {
            c.setNetworkTimeout(networkTimeoutExecutor, Math.max(0, millis));
        } catch (SQLException | RuntimeException | AbstractMethodError e) {
            LOG.trace("setNetworkTimeout not accepted: {}", e.toString());
        }
    }

    /** Releases the physical connection when the pinning rules allow it. */
    public void maybeRelease() {
        if (physical == null || closed) {
            return;
        }
        if (poolMode == PoolMode.SESSION) {
            return;
        }
        if (!cursors.isEmpty() || inTransaction) {
            return;
        }
        release(false);
    }

    /** Unconditionally returns the physical connection to its pool ({@code evict} discards a broken one). */
    public synchronized void release(boolean evict) {
        Connection c = physical;
        PhysicalPool pool = pinnedPool;
        if (c == null) {
            return;
        }
        closeAllCursors();
        closePhysicalStatements();
        savepoints.clear();
        if (!evict) {
            try {
                if (!c.getAutoCommit()) {
                    c.rollback();
                }
            } catch (SQLException | RuntimeException e) {
                LOG.debug("rollback on release failed, evicting: {}", e.toString());
                evict = true;
            }
            if (!evict) {
                try {
                    c.setAutoCommit(true);
                } catch (SQLException | RuntimeException e) {
                    LOG.debug("setAutoCommit(true) on release failed, evicting: {}", e.toString());
                    evict = true;
                }
            }
            if (!evict && settings.schema() != null && pool.defaultSchema() != null) {
                try {
                    c.setSchema(pool.defaultSchema()); // HikariCP only resets the schema when one is configured
                } catch (SQLException | RuntimeException e) {
                    LOG.debug("schema reset on release failed, evicting: {}", e.toString());
                    evict = true;
                }
            }
            if (!evict && settings.catalog() != null && pool.defaultCatalog() != null) {
                try {
                    c.setCatalog(pool.defaultCatalog());
                } catch (SQLException | RuntimeException e) {
                    LOG.debug("catalog reset on release failed, evicting: {}", e.toString());
                    evict = true;
                }
            }
            if (!evict) {
                try {
                    c.clearWarnings();
                } catch (SQLException | RuntimeException ignored) {
                    // not important
                }
                resetClientInfo(c, pool);
            }
        }
        physical = null;
        pinnedPool = null;
        pinnedFlag = false;
        inTransaction = false;
        pool.release(c, evict);
        if (pool.isDraining()) {
            pools.sweep();
        }
    }

    private void resetClientInfo(Connection c, PhysicalPool pool) {
        for (String name : appliedClientInfo) {
            try {
                c.setClientInfo(name, pool.baselineClientInfo().get(name));
            } catch (SQLException | RuntimeException ignored) {
                // best effort
            }
        }
        appliedClientInfo.clear();
    }

    /** Marks that work happened on the physical connection (a transaction is open when autocommit is off). */
    public void noteWork() {
        statements++;
        if (!settings.autoCommit()) {
            inTransaction = true;
        }
    }

    /**
     * Called when a statement failed. Evicts the physical connection when the failure indicates it is broken and
     * returns whether the session state (open transaction, SESSION mode state, open cursors) was lost, in which case
     * the handler sends a fatal ERROR and closes the session.
     */
    public boolean onSqlFailure(SQLException e) {
        if (physical == null) {
            return false;
        }
        if (!looksLikeConnectionFailure(e)) {
            return false;
        }
        boolean stateLost = inTransaction || poolMode == PoolMode.SESSION || !cursors.isEmpty();
        LOG.warn("session {}: physical connection failure ({} {}), evicting{}", id, e.getSQLState(), e.getMessage(),
                stateLost ? "; session state lost" : "");
        release(true);
        return stateLost;
    }

    private boolean looksLikeConnectionFailure(SQLException e) {
        String state = e.getSQLState();
        boolean suspicious = e instanceof SQLRecoverableException || e instanceof SQLNonTransientConnectionException
                || (state != null && state.startsWith("08") && !"08001".equals(state) && !"08004".equals(state));
        if (!suspicious) {
            return false;
        }
        try {
            return !physical.isValid(2);
        } catch (SQLException | RuntimeException ex) {
            return true;
        }
    }

    // ------------------------------------------------------------------ transactions

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        if (physical != null) {
            physical.setAutoCommit(autoCommit); // off → on commits the open transaction (JDBC semantics)
        }
        settings.autoCommit(autoCommit);
        if (autoCommit) {
            inTransaction = false;
            savepoints.clear();
        }
        maybeRelease();
    }

    public void commit() throws SQLException {
        if (physical != null && !settings.autoCommit()) {
            physical.commit();
        }
        inTransaction = false;
        savepoints.clear();
        maybeRelease();
    }

    public void rollback(String savepointName) throws SQLException {
        if (savepointName == null) {
            if (physical != null && !settings.autoCommit()) {
                physical.rollback();
            }
            inTransaction = false;
            savepoints.clear();
            maybeRelease();
            return;
        }
        Savepoint sp = savepoints.get(savepointName);
        if (sp == null || physical == null) {
            throw new SQLException("unknown savepoint '" + savepointName + "'", ErrorMessage.STATE_GENERAL);
        }
        physical.rollback(sp);
    }

    public String setSavepoint(String name) throws SQLException {
        Connection c = acquire();
        String effective = name != null ? name : "DBP_SP_" + (nextSavepointId++);
        Savepoint sp = c.setSavepoint(effective);
        noteWork();
        savepoints.put(effective, sp);
        return effective;
    }

    public void releaseSavepoint(String name) throws SQLException {
        Savepoint sp = savepoints.get(name);
        if (sp == null || physical == null) {
            throw new SQLException("unknown savepoint '" + name + "'", ErrorMessage.STATE_GENERAL);
        }
        physical.releaseSavepoint(sp);
        savepoints.remove(name);
    }

    // ------------------------------------------------------------------ session settings

    public void setTransactionIsolation(int level) throws SQLException {
        if (physical != null && level != Connection.TRANSACTION_NONE) {
            physical.setTransactionIsolation(level);
        }
        settings.transactionIsolation(level);
    }

    public void setReadOnly(boolean readOnly) throws SQLException {
        boolean effective = grantReadOnly || readOnly;
        if (physical != null) {
            physical.setReadOnly(effective);
        }
        settings.readOnly(readOnly);
    }

    public void setSchema(String schema) throws SQLException {
        if (physical != null) {
            physical.setSchema(schema);
        }
        settings.schema(schema);
    }

    public void setCatalog(String catalog) throws SQLException {
        if (physical != null) {
            physical.setCatalog(catalog);
        }
        settings.catalog(catalog);
    }

    public void setClientInfo(String name, String value) {
        settings.clientInfo(name, value);
        if (physical != null) {
            applyClientInfo(physical, pinnedPool, name, value);
        }
    }

    public void setNetworkTimeout(int millis) {
        settings.networkTimeoutMillis(millis);
        if (physical != null) {
            applyNetworkTimeout(physical, millis);
        }
    }

    /** Effective query timeout: the datasource's statementTimeoutSeconds caps the requested value. */
    public int effectiveQueryTimeout(int requested) {
        int cap = pinnedPool != null ? pinnedPool.settings().statementTimeoutSeconds() : 0;
        if (cap > 0 && (requested <= 0 || requested > cap)) {
            return cap;
        }
        return Math.max(0, requested);
    }

    // ------------------------------------------------------------------ statements

    public int prepare(String sql, StatementKind kind, int autoGeneratedKeys, List<String> keyColumns) {
        int id = nextStatementId++;
        prepared.put(id, new PreparedEntry(id, sql, kind, autoGeneratedKeys, keyColumns));
        return id;
    }

    public PreparedEntry prepared(int statementId) throws SQLException {
        PreparedEntry e = prepared.get(statementId);
        if (e == null) {
            throw new SQLException("unknown statement id " + statementId, ErrorMessage.STATE_GENERAL);
        }
        return e;
    }

    public void closeStatement(int statementId) {
        prepared.remove(statementId);
        List<Integer> toClose = new ArrayList<>();
        for (Cursor c : cursors.values()) {
            if (c.statementId() == statementId) {
                toClose.add(c.id());
            }
        }
        for (int cid : toClose) {
            closeCursorInternal(cid);
        }
        CachedStatement cs = physicalStatements.remove(statementId);
        if (cs != null) {
            closeQuietly(cs.statement());
        }
        maybeRelease();
    }

    /**
     * Returns the physical prepared/callable statement for a registered statement on the pinned connection, creating
     * (and caching) it on first use or when the generated-keys configuration changed.
     */
    public PreparedStatement physicalStatement(PreparedEntry entry, int autoGeneratedKeys, List<String> keyColumns)
            throws SQLException {
        Connection c = acquire();
        CachedStatement cached = physicalStatements.get(entry.id());
        if (cached != null) {
            if (cached.matches(autoGeneratedKeys, keyColumns)) {
                return cached.statement();
            }
            physicalStatements.remove(entry.id());
            closeQuietly(cached.statement());
        }
        PreparedStatement ps = createStatement(c, entry.sql(), entry.kind(), autoGeneratedKeys, keyColumns);
        physicalStatements.put(entry.id(), new CachedStatement(ps, autoGeneratedKeys, List.copyOf(keyColumns)));
        return ps;
    }

    /** Creates a physical prepared/callable statement (not cached). */
    public static PreparedStatement createStatement(Connection c, String sql, StatementKind kind, int autoGeneratedKeys,
                                                    List<String> keyColumns) throws SQLException {
        if (kind == StatementKind.CALLABLE) {
            return c.prepareCall(sql);
        }
        if (keyColumns != null && !keyColumns.isEmpty()) {
            return c.prepareStatement(sql, keyColumns.toArray(new String[0]));
        }
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            return c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        }
        return c.prepareStatement(sql);
    }

    private void closePhysicalStatements() {
        for (CachedStatement cs : physicalStatements.values()) {
            closeQuietly(cs.statement());
        }
        physicalStatements.clear();
    }

    // ------------------------------------------------------------------ cursors

    /** Allocates a cursor id, enforcing the per-session cap. */
    public int allocateCursorId() throws SQLException {
        if (cursors.size() >= maxOpenCursors) {
            throw new SQLException("too many open cursors (" + maxOpenCursors + ")", ErrorMessage.STATE_GENERAL);
        }
        return nextCursorId++;
    }

    public void registerCursor(Cursor cursor) {
        cursors.put(cursor.id(), cursor);
        openCursorCount = cursors.size();
    }

    public Cursor cursor(int cursorId) throws SQLException {
        Cursor c = cursors.get(cursorId);
        if (c == null) {
            throw new SQLException("unknown or closed cursor " + cursorId, ErrorMessage.STATE_GENERAL);
        }
        return c;
    }

    /** Closes a cursor (idempotent) and releases the physical connection when nothing keeps it pinned. */
    public void closeCursor(int cursorId) {
        closeCursorInternal(cursorId);
        maybeRelease();
    }

    private void closeCursorInternal(int cursorId) {
        Cursor c = cursors.remove(cursorId);
        openCursorCount = cursors.size();
        if (c == null) {
            return;
        }
        boolean closeStatement = c.ownsStatement() && c.statement() != null && !statementShared(c.statement());
        try {
            c.resultSet().close();
        } catch (SQLException | RuntimeException ignored) {
            // best effort
        }
        if (closeStatement) {
            closeQuietly(c.statement());
        }
    }

    /** Whether another open cursor still uses the statement (several result sets of one execution). */
    public boolean statementShared(Statement st) {
        for (Cursor other : cursors.values()) {
            if (other.statement() == st) {
                return true;
            }
        }
        return false;
    }

    private void closeAllCursors() {
        for (Cursor c : cursors.values()) {
            c.close();
        }
        cursors.clear();
        openCursorCount = 0;
    }

    public List<Cursor> cursors() {
        return List.copyOf(cursors.values());
    }

    // ------------------------------------------------------------------ lifecycle

    /** Closes the logical session: rollback if needed, reset the physical connection and return it to the pool. */
    public synchronized void close() {
        if (closed) {
            return;
        }
        closed = true;
        try {
            if (physical != null) {
                release(false);
            }
        } catch (RuntimeException e) {
            LOG.debug("session {} close failed: {}", id, e.toString());
        }
        prepared.clear();
    }

    static void closeQuietly(Statement st) {
        if (st == null) {
            return;
        }
        try {
            st.close();
        } catch (SQLException | RuntimeException ignored) {
            // best effort
        }
    }

    @Override
    public String toString() {
        return "LogicalSession[" + id + ", app=" + identity.application() + ", ds=" + datasource + ", mode=" + poolMode
                + (pinnedFlag ? ", pinned" : "") + ", cursors=" + openCursorCount + "]";
    }

    /** Convenience for the executor: whether a callable statement is bound. */
    public static boolean isCallable(Statement st) {
        return st instanceof CallableStatement;
    }
}
