package org.dbplatform.gateway.session;

import org.dbplatform.protocol.messages.StatementKind;

import java.util.List;

/**
 * A statement registered by PREPARE. The physical {@code PreparedStatement} is created lazily per pinned connection.
 *
 * @param id                statement id
 * @param sql               SQL text
 * @param kind              STATEMENT / PREPARED / CALLABLE
 * @param autoGeneratedKeys {@code Statement.RETURN_GENERATED_KEYS} or {@code NO_GENERATED_KEYS}
 * @param keyColumns        generated key column names (win over the flag when non-empty)
 */
public record PreparedEntry(int id, String sql, StatementKind kind, int autoGeneratedKeys, List<String> keyColumns) {

    public PreparedEntry {
        keyColumns = keyColumns == null ? List.of() : List.copyOf(keyColumns);
    }

    public boolean wantsGeneratedKeys() {
        return !keyColumns.isEmpty() || autoGeneratedKeys == java.sql.Statement.RETURN_GENERATED_KEYS;
    }
}
