package org.dbplatform.jdbc;

import org.dbplatform.protocol.messages.CloseStatement;
import org.dbplatform.protocol.messages.Execute;
import org.dbplatform.protocol.messages.ExecuteBatch;
import org.dbplatform.protocol.messages.Prepare;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.StringReader;
import java.math.BigDecimal;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.JDBCType;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class PreparedStatementTest extends GatewayTest {

    @Test
    void preparesLazilyAndExecutesByStatementId() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("select params ?, ?");
            assertThat(gateway.received(Prepare.class)).isEmpty();
            assertThat(ps.getMetaData()).isNull();

            ps.setInt(1, 7);
            ps.setString(2, "x");
            ResultSet rs = ps.executeQuery();
            assertThat(gateway.received(Prepare.class)).hasSize(1);
            Prepare p = gateway.last(Prepare.class);
            assertThat(p.sql()).isEqualTo("select params ?, ?");
            assertThat(p.kind().name()).isEqualTo("PREPARED");
            assertThat(p.autoGeneratedKeys()).isEqualTo(Statement.NO_GENERATED_KEYS);
            Execute e = gateway.last(Execute.class);
            assertThat(e.statementId()).isEqualTo(1);
            assertThat(e.sql()).isNull();
            assertThat(e.kind().name()).isEqualTo("PREPARED");
            assertThat(e.params()).containsExactly(7, "x");
            assertThat(e.options().expect()).isEqualTo(Execute.Expect.QUERY);
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString(1)).isEqualTo("Integer:7");
            assertThat(ps.getMetaData()).isNotNull();
            assertThat(ps.getMetaData().getColumnCount()).isEqualTo(2);

            ps.setInt(1, 8);
            ps.executeQuery();
            assertThat(gateway.received(Prepare.class)).hasSize(1);
            assertThat(gateway.last(Execute.class).params()).containsExactly(8, "x");

            ps.close();
            ps.close();
            assertThat(gateway.received(CloseStatement.class)).hasSize(1);
            assertThat(gateway.last(CloseStatement.class).statementId()).isEqualTo(1);
            assertThatThrownBy(ps::executeQuery).isInstanceOf(SQLException.class);
        }
    }

    @Test
    void everySetterProducesTheExpectedWireValue() throws Exception {
        try (Connection c = connect()) {
            String sql = "select params " + "?, ".repeat(28) + "?";
            PreparedStatement ps = c.prepareStatement(sql);
            int i = 1;
            ps.setNull(i++, Types.VARCHAR);
            ps.setBoolean(i++, true);
            ps.setByte(i++, (byte) 4);
            ps.setShort(i++, (short) 3);
            ps.setInt(i++, 1);
            ps.setLong(i++, 5L);
            ps.setFloat(i++, 1.5f);
            ps.setDouble(i++, 2.5d);
            ps.setBigDecimal(i++, new BigDecimal("1.50"));
            ps.setString(i++, "hello");
            ps.setBytes(i++, new byte[] {1, 2});
            ps.setDate(i++, Date.valueOf("2024-01-15"));
            ps.setTime(i++, Time.valueOf("10:20:30"));
            ps.setTimestamp(i++, Timestamp.valueOf("2024-01-15 10:20:30.5"));
            ps.setObject(i++, 42);
            ps.setObject(i++, 42, Types.VARCHAR);
            ps.setObject(i++, "12.345", Types.DECIMAL, 2);
            ps.setObject(i++, null, Types.INTEGER);
            ps.setAsciiStream(i++, new ByteArrayInputStream("ascii".getBytes(StandardCharsets.US_ASCII)));
            ps.setBinaryStream(i++, new ByteArrayInputStream(new byte[] {9, 8}), 2);
            ps.setCharacterStream(i++, new StringReader("chars"));
            ps.setBlob(i++, new DbpBlob(new byte[] {7}));
            ps.setClob(i++, new DbpClob("clob"));
            ps.setURL(i++, URI.create("http://example.org/x").toURL());
            ps.setObject(i++, UUID.fromString("123e4567-e89b-12d3-a456-426614174000"));
            ps.setObject(i++, OffsetDateTime.of(2024, 1, 15, 10, 20, 30, 0, ZoneOffset.ofHours(2)));
            ps.setObject(i++, "2024-01-15", JDBCType.DATE);
            ps.setNString(i++, "nstr");
            ps.setObject(i, LocalDate.of(2024, 2, 29));

            ResultSet rs = ps.executeQuery();
            assertThat(rs.next()).isTrue();
            int col = 1;
            assertThat(rs.getString(col++)).isEqualTo("TypedNull:12");
            assertThat(rs.getString(col++)).isEqualTo("Boolean:true");
            assertThat(rs.getString(col++)).isEqualTo("Byte:4");
            assertThat(rs.getString(col++)).isEqualTo("Short:3");
            assertThat(rs.getString(col++)).isEqualTo("Integer:1");
            assertThat(rs.getString(col++)).isEqualTo("Long:5");
            assertThat(rs.getString(col++)).isEqualTo("Float:1.5");
            assertThat(rs.getString(col++)).isEqualTo("Double:2.5");
            assertThat(rs.getString(col++)).isEqualTo("BigDecimal:1.50");
            assertThat(rs.getString(col++)).isEqualTo("String:hello");
            assertThat(rs.getString(col++)).isEqualTo("byte[]:0102");
            assertThat(rs.getString(col++)).isEqualTo("LocalDate:2024-01-15");
            assertThat(rs.getString(col++)).isEqualTo("LocalTime:10:20:30");
            assertThat(rs.getString(col++)).isEqualTo("LocalDateTime:2024-01-15T10:20:30.500");
            assertThat(rs.getString(col++)).isEqualTo("Integer:42");
            assertThat(rs.getString(col++)).isEqualTo("String:42");
            assertThat(rs.getString(col++)).isEqualTo("BigDecimal:12.35");
            assertThat(rs.getString(col++)).isEqualTo("TypedNull:4");
            assertThat(rs.getString(col++)).isEqualTo("String:ascii");
            assertThat(rs.getString(col++)).isEqualTo("byte[]:0908");
            assertThat(rs.getString(col++)).isEqualTo("String:chars");
            assertThat(rs.getString(col++)).isEqualTo("byte[]:07");
            assertThat(rs.getString(col++)).isEqualTo("String:clob");
            assertThat(rs.getString(col++)).isEqualTo("String:http://example.org/x");
            assertThat(rs.getString(col++)).isEqualTo("String:123e4567-e89b-12d3-a456-426614174000");
            assertThat(rs.getString(col++)).isEqualTo("OffsetDateTime:2024-01-15T10:20:30+02:00");
            assertThat(rs.getString(col++)).isEqualTo("LocalDate:2024-01-15");
            assertThat(rs.getString(col++)).isEqualTo("String:nstr");
            assertThat(rs.getString(col)).isEqualTo("LocalDate:2024-02-29");
        }
    }

    @Test
    void calendarVariantsUseTheCalendarZone() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("select params ?, ?, ?");
            Calendar utc = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
            // 2024-01-15T23:30Z: the local date in UTC is the 15th whatever the JVM zone is
            long millis = OffsetDateTime.of(2024, 1, 15, 23, 30, 0, 0, ZoneOffset.UTC).toInstant().toEpochMilli();
            ps.setDate(1, new Date(millis), utc);
            ps.setTimestamp(2, new Timestamp(millis), utc);
            ps.setTime(3, new Time(millis), utc);
            ResultSet rs = ps.executeQuery();
            rs.next();
            assertThat(rs.getString(1)).isEqualTo("LocalDate:2024-01-15");
            assertThat(rs.getString(2)).isEqualTo("LocalDateTime:2024-01-15T23:30");
            assertThat(rs.getString(3)).isEqualTo("LocalTime:23:30");
        }
    }

    @Test
    void unsetAndOutOfRangeParameters() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("select params ?, ?");
            ps.setInt(1, 1);
            assertThatThrownBy(ps::executeQuery)
                    .isInstanceOf(SQLException.class)
                    .satisfies(e -> assertThat(((SQLException) e).getSQLState()).isEqualTo("07001"))
                    .hasMessageContaining("parameter 2");
            ps.setInt(2, 2);
            ps.executeQuery();
            // the gateway reported 2 parameters: index 3 is now rejected
            assertThatThrownBy(() -> ps.setInt(3, 3))
                    .satisfies(e -> assertThat(((SQLException) e).getSQLState()).isEqualTo("07009"));
            assertThatThrownBy(() -> ps.setInt(0, 3)).isInstanceOf(SQLException.class);
            ps.clearParameters();
            assertThatThrownBy(ps::executeQuery).hasMessageContaining("parameter 1");
        }
    }

    @Test
    void rePreparesWhenTheGatewayForgotTheStatement() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("select params ?");
            ps.setInt(1, 1);
            ps.executeQuery();
            gateway.sessions().get(0).statements.clear();
            ps.setInt(1, 2);
            ResultSet rs = ps.executeQuery();
            rs.next();
            assertThat(rs.getString(1)).isEqualTo("Integer:2");
            assertThat(gateway.received(Prepare.class)).hasSize(2);
            assertThat(gateway.last(Execute.class).statementId()).isEqualTo(2);
            assertThat(((DbpPreparedStatement) ps).statementId()).isEqualTo(2);
        }
    }

    @Test
    void preparedBatch() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("insert into t values (?, ?)");
            assertThat(ps.executeBatch()).isEmpty();
            ps.setInt(1, 1);
            ps.setString(2, "a");
            ps.addBatch();
            ps.setInt(1, 2);
            ps.setNull(2, Types.VARCHAR);
            ps.addBatch();
            assertThat(ps.executeBatch()).containsExactly(1, 1);
            ExecuteBatch b = gateway.last(ExecuteBatch.class);
            assertThat(b.statementId()).isEqualTo(1);
            assertThat(b.kind().name()).isEqualTo("PREPARED");
            assertThat(b.sqls()).isEmpty();
            assertThat(b.paramSets()).hasSize(2);
            assertThat(b.paramSets().get(0)).containsExactly(1, "a");
            assertThat(b.paramSets().get(1).get(0)).isEqualTo(2);
            assertThat(b.paramSets().get(1).get(1)).isInstanceOf(org.dbplatform.protocol.TypedNull.class);
            assertThat(ps.executeBatch()).isEmpty();
            assertThatThrownBy(() -> ps.addBatch("insert")).satisfies(e -> assertThat(((SQLException) e).getSQLState()).isEqualTo("HY010"));

            PreparedStatement bad = c.prepareStatement("insert into missing values (?)");
            bad.setInt(1, 1);
            bad.addBatch();
            assertThatThrownBy(bad::executeLargeBatch)
                    .isInstanceOf(BatchUpdateException.class)
                    .satisfies(e -> assertThat(((BatchUpdateException) e).getLargeUpdateCounts()).isEmpty());
        }
    }

    @Test
    void generatedKeyFlagsTravelInPrepareAndExecute() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("insert into orders values (?)", Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1, 1);
            assertThat(ps.executeUpdate()).isEqualTo(1);
            assertThat(gateway.last(Prepare.class).autoGeneratedKeys()).isEqualTo(Statement.RETURN_GENERATED_KEYS);
            assertThat(gateway.last(Execute.class).options().autoGeneratedKeys()).isEqualTo(Statement.RETURN_GENERATED_KEYS);
            ResultSet keys = ps.getGeneratedKeys();
            assertThat(keys.next()).isTrue();
            assertThat(keys.getObject(1)).isEqualTo(101L);
            assertThat(keys.getObject(1, Integer.class)).isEqualTo(101);

            PreparedStatement named = c.prepareStatement("insert into orders values (?)", new String[] {"ORDER_ID"});
            named.setInt(1, 1);
            assertThat(named.execute()).isFalse();
            assertThat(gateway.last(Prepare.class).generatedKeyColumns()).containsExactly("ORDER_ID");
            assertThat(gateway.last(Execute.class).options().generatedKeyColumns()).containsExactly("ORDER_ID");
            assertThat(named.getGeneratedKeys().getMetaData().getColumnLabel(1)).isEqualTo("ORDER_ID");
        }
    }

    @Test
    void parameterMetaDataAndUnsupportedSetters() throws Exception {
        try (Connection c = connect()) {
            PreparedStatement ps = c.prepareStatement("select params ?, ?, ?");
            ParameterMetaData pmd = ps.getParameterMetaData();
            assertThat(gateway.received(Prepare.class)).hasSize(1);
            assertThat(pmd.getParameterCount()).isEqualTo(3);
            assertThat(pmd.getParameterMode(1)).isEqualTo(ParameterMetaData.parameterModeUnknown);
            assertThat(pmd.getParameterType(2)).isEqualTo(Types.OTHER);
            assertThat(pmd.getParameterClassName(3)).isEqualTo("java.lang.Object");
            assertThatThrownBy(() -> pmd.getParameterType(4)).isInstanceOf(SQLException.class);

            assertThatThrownBy(() -> ps.setArray(1, null)).isInstanceOf(SQLFeatureNotSupportedException.class);
            assertThatThrownBy(() -> ps.setRef(1, null)).isInstanceOf(SQLFeatureNotSupportedException.class);
            assertThatThrownBy(() -> ps.setRowId(1, null)).isInstanceOf(SQLFeatureNotSupportedException.class);
            assertThatThrownBy(() -> ps.setSQLXML(1, null)).isInstanceOf(SQLFeatureNotSupportedException.class);
            assertThatThrownBy(() -> ps.executeQuery("select 1")).satisfies(e -> assertThat(((SQLException) e).getSQLState()).isEqualTo("HY010"));
            assertThatThrownBy(() -> ps.execute("select 1")).isInstanceOf(SQLException.class);
            assertThat(ps.toString()).contains("DbpPreparedStatement");
        }
    }
}
