package org.dbplatform.protocol.messages;

import org.dbplatform.protocol.MessageType;
import org.dbplatform.protocol.ProtocolConstants;
import org.dbplatform.protocol.ProtocolException;
import org.dbplatform.protocol.ProtocolInput;
import org.dbplatform.protocol.ProtocolOutput;

import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * EXECUTE (0x11): {@code i32 statementId (-1 = direct SQL), string sql (null unless direct), u8 kind,
 * Value[] params, ExecOptions, OutParam[]}. Answered by the sequence
 * {@code (RESULT_SET_HEADER ROWS | UPDATE_COUNT)* OUT_PARAMS? GENERATED_KEYS? EXECUTE_DONE} or ERROR.
 *
 * @param statementId registered statement id, or {@link ProtocolConstants#DIRECT_STATEMENT_ID} for direct SQL
 * @param sql         SQL text for direct execution, {@code null} when a registered statement is used
 * @param kind        statement flavour
 * @param params      parameter values in order (elements may be {@code null} or {@link org.dbplatform.protocol.TypedNull})
 * @param options     execution options, never {@code null}
 * @param outParams   registered OUT parameters (CALLABLE only), never {@code null}
 */
public record Execute(int statementId, String sql, StatementKind kind, List<Object> params, ExecOptions options,
                      List<OutParam> outParams) implements Message {

    /**
     * How the client called the statement; the gateway invokes the matching physical JDBC method and validates
     * the result shape ({@code executeQuery} on an UPDATE yields ERROR {@code 07005}).
     */
    public enum Expect {
        /** {@code execute()}: any result shape. */
        ANY(0),
        /** {@code executeQuery()}: exactly one result set. */
        QUERY(1),
        /** {@code executeUpdate()}: an update count. */
        UPDATE(2);

        private final int code;

        Expect(int code) {
            this.code = code;
        }

        /**
         * Returns the wire code.
         *
         * @return {@code 0..2}
         */
        public int code() {
            return code;
        }

        /**
         * Resolves a wire code.
         *
         * @param code the byte read
         * @return the constant
         * @throws ProtocolException if unknown
         */
        public static Expect fromCode(int code) throws ProtocolException {
            return switch (code) {
                case 0 -> ANY;
                case 1 -> QUERY;
                case 2 -> UPDATE;
                default -> throw new ProtocolException("unknown expect code " + code);
            };
        }
    }

    /**
     * {@code ExecOptions := i32 maxRows, i32 fetchSize, i32 queryTimeoutSeconds, u8 expect, i32 autoGeneratedKeys,
     * string[] generatedKeyColumns}.
     *
     * @param maxRows             {@code Statement.setMaxRows}, 0 = unlimited
     * @param fetchSize           rows returned with the header and per FETCH; {@code <= 0} = gateway default (100)
     * @param queryTimeoutSeconds {@code Statement.setQueryTimeout}, 0 = none
     * @param expect              which JDBC method was called
     * @param autoGeneratedKeys   {@link Statement#NO_GENERATED_KEYS} or {@link Statement#RETURN_GENERATED_KEYS}
     * @param generatedKeyColumns requested generated key columns; non-empty wins over the flag
     */
    public record ExecOptions(int maxRows, int fetchSize, int queryTimeoutSeconds, Expect expect, int autoGeneratedKeys,
                              List<String> generatedKeyColumns) {

        /** Defaults: no limits, {@link Expect#ANY}, no generated keys. */
        public static final ExecOptions DEFAULT =
                new ExecOptions(0, 0, 0, Expect.ANY, Statement.NO_GENERATED_KEYS, List.of());

        /**
         * Validates and normalises.
         *
         * @param maxRows             see record
         * @param fetchSize           see record
         * @param queryTimeoutSeconds see record
         * @param expect              non-null
         * @param autoGeneratedKeys   see record
         * @param generatedKeyColumns {@code null} = empty
         */
        public ExecOptions {
            if (expect == null) {
                throw new IllegalArgumentException("expect must not be null");
            }
            generatedKeyColumns = Codec.copyList(generatedKeyColumns);
        }

        /**
         * Returns a copy with another {@code expect}.
         *
         * @param e the expectation
         * @return new options
         */
        public ExecOptions withExpect(Expect e) {
            return new ExecOptions(maxRows, fetchSize, queryTimeoutSeconds, e, autoGeneratedKeys, generatedKeyColumns);
        }

        /**
         * Writes the structure.
         *
         * @param out destination
         */
        public void encode(ProtocolOutput out) {
            out.writeI32(maxRows)
                    .writeI32(fetchSize)
                    .writeI32(queryTimeoutSeconds)
                    .writeU8(expect.code())
                    .writeI32(autoGeneratedKeys)
                    .writeStringArray(generatedKeyColumns);
        }

        /**
         * Reads the structure.
         *
         * @param in source
         * @return the options
         * @throws ProtocolException if malformed
         */
        public static ExecOptions decode(ProtocolInput in) throws ProtocolException {
            int maxRows = in.readI32();
            int fetchSize = in.readI32();
            int queryTimeout = in.readI32();
            Expect expect = Expect.fromCode(in.readU8());
            int autoGeneratedKeys = in.readI32();
            List<String> cols = in.readStringArray();
            return new ExecOptions(maxRows, fetchSize, queryTimeout, expect, autoGeneratedKeys, cols);
        }
    }

    /**
     * {@code OutParam := i32 index (1-based), i32 jdbcType, i32 scale (-1 none), string typeName (nullable)}.
     * The gateway calls {@code CallableStatement.registerOutParameter} accordingly.
     *
     * @param index    1-based parameter index
     * @param jdbcType {@link java.sql.Types} constant
     * @param scale    scale, or {@link ProtocolConstants#NO_SCALE}
     * @param typeName user-defined type name, or {@code null}
     */
    public record OutParam(int index, int jdbcType, int scale, String typeName) {

        /** Minimum encoded size: three i32 plus a null string. */
        static final int MIN_BYTES = 4 + 4 + 4 + 4;

        /**
         * Creates an OUT parameter registration without scale or type name.
         *
         * @param index    1-based index
         * @param jdbcType JDBC type
         * @return the registration
         */
        public static OutParam of(int index, int jdbcType) {
            return new OutParam(index, jdbcType, ProtocolConstants.NO_SCALE, null);
        }

        /**
         * Writes the structure.
         *
         * @param out destination
         */
        public void encode(ProtocolOutput out) {
            out.writeI32(index).writeI32(jdbcType).writeI32(scale).writeString(typeName);
        }

        /**
         * Reads the structure.
         *
         * @param in source
         * @return the registration
         * @throws ProtocolException if malformed
         */
        public static OutParam decode(ProtocolInput in) throws ProtocolException {
            int index = in.readI32();
            int jdbcType = in.readI32();
            int scale = in.readI32();
            String typeName = in.readString();
            return new OutParam(index, jdbcType, scale, typeName);
        }
    }

    /**
     * Validates and normalises.
     *
     * @param statementId see record
     * @param sql         see record
     * @param kind        non-null
     * @param params      {@code null} = empty
     * @param options     {@code null} = {@link ExecOptions#DEFAULT}
     * @param outParams   {@code null} = empty
     */
    public Execute {
        if (kind == null) {
            throw new IllegalArgumentException("kind must not be null");
        }
        if (statementId == ProtocolConstants.DIRECT_STATEMENT_ID && sql == null) {
            throw new IllegalArgumentException("direct execution requires sql");
        }
        params = Codec.copyList(params);
        options = options == null ? ExecOptions.DEFAULT : options;
        outParams = Codec.copyList(outParams);
    }

    /**
     * Creates a direct (unregistered) execution.
     *
     * @param sql     SQL text
     * @param kind    statement flavour
     * @param params  parameters
     * @param options options
     * @return the message
     */
    public static Execute direct(String sql, StatementKind kind, List<Object> params, ExecOptions options) {
        return new Execute(ProtocolConstants.DIRECT_STATEMENT_ID, sql, kind, params, options, List.of());
    }

    /**
     * Creates an execution of a registered statement.
     *
     * @param statementId id returned in PREPARED
     * @param kind        statement flavour
     * @param params      parameters
     * @param options     options
     * @return the message
     */
    public static Execute prepared(int statementId, StatementKind kind, List<Object> params, ExecOptions options) {
        return new Execute(statementId, null, kind, params, options, List.of());
    }

    /**
     * Returns whether this execution carries its own SQL.
     *
     * @return {@code true} if {@link #statementId()} is {@link ProtocolConstants#DIRECT_STATEMENT_ID}
     */
    public boolean isDirect() {
        return statementId == ProtocolConstants.DIRECT_STATEMENT_ID;
    }

    @Override
    public MessageType type() {
        return MessageType.EXECUTE;
    }

    @Override
    public void encode(ProtocolOutput out) {
        out.writeI32(statementId).writeString(sql).writeU8(kind.code()).writeValues(params);
        options.encode(out);
        out.writeI32(outParams.size());
        for (OutParam p : outParams) {
            p.encode(out);
        }
    }

    /**
     * Decodes the payload.
     *
     * @param in source
     * @return the message
     * @throws ProtocolException if malformed
     */
    public static Execute decode(ProtocolInput in) throws ProtocolException {
        int statementId = in.readI32();
        String sql = in.readString();
        StatementKind kind = StatementKind.fromCode(in.readU8());
        List<Object> params = in.readValues();
        ExecOptions options = ExecOptions.decode(in);
        int n = in.readCount("OutParam", OutParam.MIN_BYTES);
        List<OutParam> outParams = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            outParams.add(OutParam.decode(in));
        }
        if (statementId == ProtocolConstants.DIRECT_STATEMENT_ID && sql == null) {
            throw new ProtocolException("EXECUTE with statementId -1 must carry sql");
        }
        return new Execute(statementId, sql, kind, params, options, outParams);
    }
}
