package org.dbplatform.protocol.messages;

import org.dbplatform.protocol.MessageType;
import org.dbplatform.protocol.ProtocolException;
import org.dbplatform.protocol.ProtocolInput;
import org.dbplatform.protocol.ProtocolOutput;

import java.sql.Statement;
import java.util.List;

/**
 * PREPARE (0x10): {@code string sql, u8 kind, i32 autoGeneratedKeys, string[] generatedKeyColumns},
 * answered by PREPARED. Registers SQL with the gateway without touching the physical database.
 *
 * @param sql                 the SQL text, never {@code null}
 * @param kind                PREPARED or CALLABLE (STATEMENT is accepted but unusual)
 * @param autoGeneratedKeys   {@link Statement#NO_GENERATED_KEYS} or {@link Statement#RETURN_GENERATED_KEYS}
 * @param generatedKeyColumns requested generated key columns; when non-empty it wins over the flag
 */
public record Prepare(String sql, StatementKind kind, int autoGeneratedKeys, List<String> generatedKeyColumns)
        implements Message {

    /**
     * Validates and normalises.
     *
     * @param sql                 non-null SQL
     * @param kind                non-null kind
     * @param autoGeneratedKeys   see record
     * @param generatedKeyColumns {@code null} = empty
     */
    public Prepare {
        if (sql == null) {
            throw new IllegalArgumentException("sql must not be null");
        }
        if (kind == null) {
            throw new IllegalArgumentException("kind must not be null");
        }
        generatedKeyColumns = Codec.copyList(generatedKeyColumns);
    }

    /**
     * Creates a PREPARE without generated-key request.
     *
     * @param sql  SQL
     * @param kind kind
     * @return the message
     */
    public static Prepare of(String sql, StatementKind kind) {
        return new Prepare(sql, kind, Statement.NO_GENERATED_KEYS, List.of());
    }

    @Override
    public MessageType type() {
        return MessageType.PREPARE;
    }

    @Override
    public void encode(ProtocolOutput out) {
        out.writeString(sql).writeU8(kind.code()).writeI32(autoGeneratedKeys).writeStringArray(generatedKeyColumns);
    }

    /**
     * Decodes the payload.
     *
     * @param in source
     * @return the message
     * @throws ProtocolException if malformed
     */
    public static Prepare decode(ProtocolInput in) throws ProtocolException {
        String sql = in.readString();
        if (sql == null) {
            throw new ProtocolException("PREPARE sql must not be null");
        }
        StatementKind kind = StatementKind.fromCode(in.readU8());
        int autoGeneratedKeys = in.readI32();
        List<String> cols = in.readStringArray();
        return new Prepare(sql, kind, autoGeneratedKeys, cols);
    }
}
